// rebuild_all_vocab.js
// Replaces the vocabulary section of every scenario with a complete, curated, premium list of vocabulary items (approx. 20-25 items per scenario).
// Every vocabulary item contains: english, portuguese, sentenceA1, sentenceA2, sentenceA1Pt, sentenceA2Pt.

const fs = require('fs');

const ids = ['introduction','numbers','airport','immigration','hotel','restaurant','directions','transport','medical','entertainment','cafe','tech','smalltalk','slangs','shopping','beauty','carrental','supermarket'];

const newVocabularies = {
  introduction: [
    { english: "My name is...", portuguese: "Meu nome é...", sentenceA1: "My name is Maria.", sentenceA2: "My name is Maria and I am from São Paulo.", sentenceA1Pt: "Meu nome é Maria.", sentenceA2Pt: "Meu nome é Maria e eu sou de São Paulo." },
    { english: "Nice to meet you", portuguese: "Prazer em conhecê-lo(a)", sentenceA1: "Nice to meet you, John.", sentenceA2: "Nice to meet you! I heard a lot about you.", sentenceA1Pt: "Prazer em conhecê-lo, John.", sentenceA2Pt: "Prazer em conhecê-lo! Eu ouvi muito sobre você." },
    { english: "I'm from Brazil", portuguese: "Eu sou do Brasil", sentenceA1: "I'm from Brazil.", sentenceA2: "I'm from Brazil, but I have been living in the US for two years.", sentenceA1Pt: "Eu sou do Brasil.", sentenceA2Pt: "Sou do Brasil, mas moro nos EUA há dois anos." },
    { english: "How old are you?", portuguese: "Quantos anos você tem?", sentenceA1: "How old are you? I am 25.", sentenceA2: "How old are you? You look very young for your age.", sentenceA1Pt: "Quantos anos você tem? Eu tenho 25.", sentenceA2Pt: "Quantos anos você tem? Você parece muito jovem para a sua idade." },
    { english: "I'm ... years old", portuguese: "Eu tenho ... anos", sentenceA1: "I'm 30 years old.", sentenceA2: "I'm 28 years old and I work as an engineer.", sentenceA1Pt: "Eu tenho 30 anos.", sentenceA2Pt: "Tenho 28 anos e trabalho como engenheiro(a)." },
    { english: "What do you do?", portuguese: "O que você faz?", sentenceA1: "What do you do? I am a teacher.", sentence2: "What do you do for a living? I work in marketing.", sentenceA1: "What do you do? I am a teacher.", sentenceA2: "What do you do for a living? I work in marketing.", sentenceA1Pt: "O que você faz? Eu sou professor(a).", sentenceA2Pt: "O que você faz profissionalmente? Eu trabalho com marketing." },
    { english: "First time", portuguese: "Primeira vez", sentenceA1: "Is this your first time here?", sentenceA2: "Is this your first time visiting the United States?", sentenceA1Pt: "É a sua primeira vez aqui?", sentenceA2Pt: "É a sua primeira vez visitando os Estados Unidos?" },
    { english: "I'm excited", portuguese: "Estou animado(a)", sentenceA1: "I'm excited about this trip!", sentenceA2: "I'm really excited to be here for the first time.", sentenceA1Pt: "Estou animado(a) com esta viagem!", sentenceA2Pt: "Estou muito animado(a) de estar aqui pela primeira vez." },
    { english: "Last name / Surname", portuguese: "Sobrenome", sentenceA1: "My last name is Silva.", sentenceA2: "Could you spell your last name for me, please?", sentenceA1Pt: "Meu sobrenome é Silva.", sentenceA2Pt: "Você poderia soletrar seu sobrenome para mim, por favor?" },
    { english: "Nickname", portuguese: "Apelido", sentenceA1: "My nickname is Leo.", sentenceA2: "Everyone calls me by my nickname instead of my full name.", sentenceA1Pt: "Meu apelido é Leo.", sentenceA2Pt: "Todo mundo me chama pelo apelido em vez do nome completo." },
    { english: "Married", portuguese: "Casado(a)", sentenceA1: "I am married.", sentenceA2: "I have been married for five years and we have two kids.", sentenceA1Pt: "Eu sou casado(a).", sentenceA2Pt: "Eu sou casado(a) há cinco anos e temos dois filhos." },
    { english: "Single", portuguese: "Solteiro(a)", sentenceA1: "I am single.", sentenceA2: "I am single right now, but I am not looking for a relationship.", sentenceA1Pt: "Eu sou solteiro(a).", sentenceA2Pt: "Eu sou solteiro(a) agora, mas não estou procurando um relacionamento." },
    { english: "Hometown", portuguese: "Cidade natal", sentenceA1: "My hometown is Rio.", sentenceA2: "My hometown is a small city in the south of Brazil.", sentenceA1Pt: "Minha cidade natal é o Rio.", sentenceA2Pt: "Minha cidade natal é uma cidade pequena no sul do Brasil." },
    { english: "Nice to meet you too", portuguese: "Prazer em conhecê-lo(a) também", sentenceA1: "Nice to meet you too!", sentenceA2: "Nice to meet you too! I hope we can work together.", sentenceA1Pt: "Prazer em conhecê-lo(a) também!", sentenceA2Pt: "Prazer em conhecê-lo(a) também! Espero que possamos trabalhar juntos." },
    // New ones:
    { english: "Occupation", portuguese: "Profissão / Ocupação", sentenceA1: "What is your occupation?", sentenceA2: "Please write your current occupation on this form.", sentenceA1Pt: "Qual é a sua profissão?", sentenceA2Pt: "Por favor, escreva sua profissão atual neste formulário." },
    { english: "Country of origin", portuguese: "País de origem", sentenceA1: "My country of origin is Brazil.", sentenceA2: "You must state your country of origin on your passport profile.", sentenceA1Pt: "Meu país de origem é o Brasil.", sentenceA2Pt: "Você deve declarar seu país de origem no perfil do seu passaporte." },
    { english: "Full name", portuguese: "Nome completo", sentenceA1: "What is your full name?", sentenceA2: "Please write your full name as it appears on your passport.", sentenceA1Pt: "Qual é o seu nome completo?", sentenceA2Pt: "Por favor, escreva seu nome completo como aparece no seu passaporte." },
    { english: "Address", portuguese: "Endereço", sentenceA1: "What is your address?", sentenceA2: "I need to confirm your temporary address during your stay.", sentenceA1Pt: "Qual é o seu endereço?", sentenceA2Pt: "Preciso confirmar seu endereço temporário durante a sua estadia." },
    { english: "Phone number", portuguese: "Número de telefone", sentenceA1: "My phone number is 555-1234.", sentenceA2: "Can you give me your international phone number?", sentenceA1Pt: "Meu número de telefone é 555-1234.", sentenceA2Pt: "Você pode me dar o seu número de telefone internacional?" },
    { english: "Email address", portuguese: "Endereço de e-mail", sentenceA1: "What is your email address?", sentenceA2: "We will send the confirmation to your email address.", sentenceA1Pt: "Qual é o seu e-mail?", sentenceA2Pt: "Nós enviaremos a confirmação para o seu endereço de e-mail." },
    { english: "Divorced", portuguese: "Divorciado(a)", sentenceA1: "She is divorced.", sentenceA2: "He got divorced last year but remains good friends with his ex-wife.", sentenceA1Pt: "Ela é divorciada.", sentenceA2Pt: "Ele se divorciou ano passado mas continua muito amigo da ex-esposa." },
    { english: "Date of birth", portuguese: "Data de nascimento", sentenceA1: "My date of birth is July 4th.", sentenceA2: "Please verify that your date of birth is correct on the document.", sentenceA1Pt: "Minha data de nascimento é 4 de julho.", sentenceA2Pt: "Por favor, verifique se a sua data de nascimento está correta no documento." }
  ],
  numbers: [
    { english: "How much?", portuguese: "Quanto?", sentenceA1: "How much is this?", sentenceA2: "How much does this shirt cost with the discount?", sentenceA1Pt: "Quanto custa isso?", sentenceA2Pt: "Quanto custa esta camisa com o desconto?" },
    { english: "Dollar", portuguese: "Dólar", sentenceA1: "It costs ten dollars.", sentenceA2: "The exchange rate is five reais per dollar today.", sentenceA1Pt: "Custa dez dólares.", sentenceA2Pt: "La taxa de câmbio é de cinco reais por dólar hoje." },
    { english: "Cents", portuguese: "Centavos", sentenceA1: "That is fifty cents.", sentenceA2: "Your change is seventy-five cents.", sentenceA1Pt: "São cinquenta centavos.", sentenceA2Pt: "Seu troco é de setenta e cinco centavos." },
    { english: "Receipt", portuguese: "Recibo / Nota fiscal", sentenceA1: "Can I have the receipt?", sentenceA2: "I need the receipt for my expense report.", sentenceA1Pt: "Posso ter o recibo?", sentenceA2Pt: "Preciso do recibo para o relatório de despesas." },
    { english: "Change", portuguese: "Troco", sentenceA1: "Here is your change.", sentenceA2: "Keep the change, please. It is your tip.", sentenceA1Pt: "Aqui está o seu troco.", sentenceA2Pt: "Fique com o troco, por favor. É a sua gorjeta." },
    { english: "Credit card", portuguese: "Cartão de crédito", sentenceA1: "I pay with credit card.", sentenceA2: "Do you accept credit cards or only cash?", sentenceA1Pt: "Eu pago com cartão.", sentenceA2Pt: "Vocês aceitam cartões de crédito ou apenas dinheiro?" },
    { english: "Per pound", portuguese: "Por libra", sentenceA1: "It is two dollars per pound.", sentenceA2: "The fresh salmon is twelve dollars per pound.", sentenceA1Pt: "São dois dólares por libra.", sentenceA2Pt: "O salmão fresco custa doze dólares por libra." },
    { english: "Total", portuguese: "Total", sentenceA1: "The total is twenty dollars.", sentenceA2: "Your total comes to forty-five dollars and thirty cents.", sentenceA1Pt: "O total é vinte dólares.", sentenceA2Pt: "Seu total é de quarenta e cinco dólares e trinta centavos." },
    { english: "Cash", portuguese: "Dinheiro em espécie", sentenceA1: "I pay in cash.", sentenceA2: "I prefer to pay in cash so I can control my spending.", sentenceA1Pt: "Eu pago em dinheiro.", sentenceA2Pt: "Prefiro pagar em dinheiro para controlar meus gastos." },
    { english: "Discount", portuguese: "Desconto", sentenceA1: "Is there a discount?", sentenceA2: "Students get a twenty percent discount on all items.", sentenceA1Pt: "Tem desconto?", sentenceA2Pt: "Estudantes ganham vinte por cento de desconto em todos os itens." },
    { english: "On sale", portuguese: "Em promoção", sentenceA1: "This is on sale.", sentenceA2: "These shoes are on sale this weekend for half price.", sentenceA1Pt: "Isto está em promoção.", sentenceA2Pt: "Estes sapatos estão em promoção pela metade do preço." },
    { english: "Expensive", portuguese: "Caro", sentenceA1: "This is very expensive.", sentenceA2: "The restaurant is expensive but the food is delicious.", sentenceA1Pt: "Isto é muito caro.", sentenceA2Pt: "O restaurante é caro, mas a comida é deliciosa." },
    { english: "Cheap", portuguese: "Barato", sentenceA1: "This is very cheap.", sentenceA2: "The street food here is cheap and really tasty.", sentenceA1Pt: "Isto é muito barato.", sentenceA2Pt: "A comida de rua aqui é barata e muito saborosa." },
    { english: "Cashier", portuguese: "Caixa / Atendente", sentenceA1: "The cashier is over there.", sentenceA2: "Please pay the cashier at the front of the store.", sentenceA1Pt: "O caixa é ali.", sentenceA2Pt: "Por favor, pague no caixa na frente da loja." },
    { english: "Shopping cart", portuguese: "Carrinho de compras", sentenceA1: "I need a shopping cart.", sentenceA2: "Could you grab a shopping cart? We have a lot to buy.", sentenceA1Pt: "Preciso de um carrinho.", sentenceA2Pt: "Pode pegar um carrinho? Temos muita coisa para comprar." },
    // New ones:
    { english: "Price tag", portuguese: "Etiqueta de preço", sentenceA1: "Where is the price tag?", sentenceA2: "This shirt doesn't have a price tag. Could you check the price for me?", sentenceA1Pt: "Onde está a etiqueta?", sentenceA2Pt: "Esta camisa está sem etiqueta. Você poderia checar o preço para mim?" },
    { english: "Debit card", portuguese: "Cartão de débito", sentenceA1: "Can I pay by debit card?", sentenceA2: "My debit card didn't work, so I had to pay with cash.", sentenceA1Pt: "Posso pagar com cartão de débito?", sentenceA2Pt: "Meu cartão de débito não funcionou, então precisei pagar em dinheiro." },
    { english: "Sales tax", portuguese: "Imposto sobre vendas", sentenceA1: "How much is the sales tax?", sentenceA2: "Remember that the sales tax is added at the register, not on the tag.", sentenceA1Pt: "Quanto é o imposto de vendas?", sentenceA2Pt: "Lembre-se de que o imposto de vendas é adicionado no caixa, não na etiqueta." },
    { english: "Refund", portuguese: "Reembolso", sentenceA1: "I want a refund.", sentenceA2: "If you bring the receipt, you can get a full refund within thirty days.", sentenceA1Pt: "Quero um reembolso.", sentenceA2Pt: "Se você trouxer o recibo, pode receber um reembolso total em trinta dias." },
    { english: "Billing address", portuguese: "Endereço de cobrança", sentenceA1: "What is your billing address?", sentenceA2: "The system requires your billing address to process the credit card.", sentenceA1Pt: "Qual é o endereço de cobrança?", sentenceA2Pt: "O sistema exige seu endereço de cobrança para processar o cartão de crédito." }
  ],
  airport: [
    { english: "Boarding pass", portuguese: "Cartão de embarque", sentenceA1: "Here is my boarding pass.", sentenceA2: "You can download your boarding pass on the airline app.", sentenceA1Pt: "Aqui está meu cartão de embarque.", sentenceA2Pt: "Você pode baixar o cartão de embarque no app da companhia." },
    { english: "Baggage claim", portuguese: "Esteira de bagagem", sentenceA1: "Where is baggage claim?", sentenceA2: "My suitcase was not at the baggage claim when I arrived.", sentenceA1Pt: "Onde é a esteira de bagagem?", sentenceA2Pt: "Minha mala não estava na esteira quando cheguei." },
    { english: "Gate", portuguese: "Portão", sentenceA1: "The gate is B5.", sentenceA2: "They changed the gate from A3 to B12 at the last minute.", sentenceA1Pt: "O portão é B5.", sentenceA2Pt: "Mudaram o portão de A3 para B12 no último minuto." },
    { english: "Flight", portuguese: "Voo", sentenceA1: "My flight is at 3 PM.", sentenceA2: "My connecting flight leaves in two hours from terminal C.", sentenceA1Pt: "Meu voo é às 15h.", sentenceA2Pt: "Meu voo de conexão sai em duas horas do terminal C." },
    { english: "Luggage / Suitcase", portuguese: "Mala / Bagagem", sentenceA1: "I have one suitcase.", sentenceA2: "I packed all my luggage last night to avoid rushing.", sentenceA1Pt: "Eu tenho uma mala.", sentenceA2Pt: "Fiz todas as malas ontem à noite para não correr." },
    { english: "Carry-on", portuguese: "Bagagem de mão", sentenceA1: "This is my carry-on.", sentenceA2: "You are only allowed one carry-on and one personal item.", sentenceA1Pt: "Esta é minha bagagem de mão.", sentenceA2Pt: "Só é permitida uma bagagem de mão e um item pessoal." },
    { english: "Security check", portuguese: "Segurança / Controle", sentenceA1: "Where is security check?", sentenceA2: "The security check line was very long this morning.", sentenceA1Pt: "Onde é a segurança?", sentenceA2Pt: "A fila da segurança estava muito longa hoje de manhã." },
    { english: "X-ray machine", portuguese: "Máquina de raio-X", sentenceA1: "Put your bag on the X-ray.", sentenceA2: "The officer asked me to send my laptop through the X-ray separately.", sentenceA1Pt: "Coloque a bolsa no raio-X.", sentenceA2Pt: "O agente pediu para passar meu notebook no raio-X separadamente." },
    { english: "Liquids", portuguese: "Líquidos", sentenceA1: "No liquids over 100ml.", sentenceA2: "All liquids must be in containers of 100ml or less.", sentenceA1Pt: "Sem líquidos acima de 100ml.", sentenceA2Pt: "Todos os líquidos devem estar em recipientes de 100ml ou menos." },
    { english: "Electronics", portuguese: "Eletrônicos", sentenceA1: "Remove your electronics.", sentenceA2: "Please take all large electronics out of your bag.", sentenceA1Pt: "Retire seus eletrônicos.", sentenceA2Pt: "Retire todos os eletrônicos grandes da sua bolsa." },
    { english: "Take off your shoes", portuguese: "Tirar os sapatos", sentenceA1: "Take off your shoes, please.", sentenceA2: "At some airports you need to take off your shoes at security.", sentenceA1Pt: "Tire seus sapatos, por favor.", sentenceA2Pt: "Em alguns aeroportos você precisa tirar os sapatos na segurança." },
    { english: "Belt", portuguese: "Cinto", sentenceA1: "Remove your belt.", sentenceA2: "I always forget to remove my belt and it sets off the alarm.", sentenceA1Pt: "Retire o cinto.", sentenceA2Pt: "Sempre esqueço de tirar meu cinto e ele dispara o alarme." },
    { english: "Overweight baggage", portuguese: "Excesso de peso", sentenceA1: "My bag is overweight.", sentenceA2: "They charged me fifty dollars for overweight baggage.", sentenceA1Pt: "Minha mala está com excesso de peso.", sentenceA2Pt: "Me cobraram cinquenta dólares por excesso de bagagem." },
    { english: "Delayed", portuguese: "Atrasado", sentenceA1: "My flight is delayed.", sentenceA2: "The flight was delayed by three hours due to bad weather.", sentenceA1Pt: "Meu voo está atrasado.", sentenceA2Pt: "O voo atrasou três horas por causa do mau tempo." },
    { english: "On time", portuguese: "No horário / Pontual", sentenceA1: "The flight is on time.", sentenceA2: "I checked the app and my flight is on time.", sentenceA1Pt: "O voo está no horário.", sentenceA2Pt: "Verifiquei o app e meu voo está no horário." },
    { english: "Aisle seat", portuguese: "Assento no corredor", sentenceA1: "I want an aisle seat.", sentenceA2: "Can I switch to an aisle seat? I need to get up frequently.", sentenceA1Pt: "Quero assento no corredor.", sentenceA2Pt: "Posso trocar para corredor? Preciso levantar frequentemente." },
    { english: "Window seat", portuguese: "Assento na janela", sentenceA1: "I prefer a window seat.", sentenceA2: "I always book a window seat to enjoy the view.", sentenceA1Pt: "Prefiro assento na janela.", sentenceA2Pt: "Sempre reservo janela para aproveitar a vista." },
    // New ones:
    { english: "Customs declaration", portuguese: "Declaração de alfândega", sentenceA1: "Do I need a customs card?", sentenceA2: "You must complete a customs declaration form before exiting.", sentenceA1Pt: "Preciso de um cartão de alfândega?", sentenceA2Pt: "Você deve preencher um formulário de declaração de alfândega antes de sair." },
    { english: "Layover", portuguese: "Conexão / Escala", sentenceA1: "I have a three-hour layover.", sentenceA2: "Our layover in Atlanta is very short, so we have to run.", sentenceA1Pt: "Tenho uma escala de três horas.", sentenceA2Pt: "Nossa escala em Atlanta é muito curta, então temos que correr." },
    { english: "Terminal", portuguese: "Terminal", sentenceA1: "Which terminal is it?", sentenceA2: "International flights depart from Terminal 4 at this airport.", sentenceA1Pt: "Qual terminal é?", sentenceA2Pt: "Voos internacionais partem do Terminal 4 neste aeroporto." },
    { english: "Boarding group", portuguese: "Grupo de embarque", sentenceA1: "My boarding group is C.", sentenceA2: "Please wait until your boarding group is called by the gate agent.", sentenceA1Pt: "Meu grupo de embarque é C.", sentenceA2Pt: "Por favor, aguarde até que seu grupo de embarque seja chamado pelo agente do portão." },
    { english: "Duty-free shop", portuguese: "Loja franca / Duty-free", sentenceA1: "Where is the duty-free?", sentenceA2: "I bought some chocolate at the duty-free shop before boarding.", sentenceA1Pt: "Onde é o duty-free?", sentenceA2Pt: "Comprei chocolate na loja duty-free antes de embarcar." }
  ],
  immigration: [
    { english: "Passport", portuguese: "Passaporte", sentenceA1: "Here is my passport.", sentenceA2: "My passport is valid for another three years.", sentenceA1Pt: "Aqui está meu passaporte.", sentenceA2Pt: "Meu passaporte é válido por mais três anos." },
    { english: "Customs", portuguese: "Alfândega", sentenceA1: "Where is customs?", sentenceA2: "I declared two bottles of wine at customs.", sentenceA1Pt: "Onde é a alfândega?", sentenceA2Pt: "Declarei duas garrafas de vinho na alfândega." },
    { english: "Arrival", portuguese: "Chegada", sentenceA1: "My arrival is today.", sentenceA2: "The arrival terminal is on the first floor.", sentenceA1Pt: "Minha chegada é hoje.", sentenceA2Pt: "O terminal de chegada é no primeiro andar." },
    { english: "Departure", portuguese: "Partida", sentenceA1: "My departure is Friday.", sentenceA2: "The departure lounge has free Wi-Fi.", sentenceA1Pt: "Minha partida é sexta.", sentenceA2Pt: "A sala de embarque tem Wi-Fi gratuito." },
    { english: "Purpose of visit", portuguese: "Motivo da visita", sentenceA1: "I am here for tourism.", sentenceA2: "The purpose of my visit is to attend a conference.", sentenceA1Pt: "Estou aqui para turismo.", sentenceA2Pt: "O propósito da minha visita é participar de uma conferência." },
    { english: "Duration of stay", portuguese: "Duração da estadia", sentenceA1: "I will stay two weeks.", sentenceA2: "The duration of my stay is approximately fifteen days.", sentenceA1Pt: "Vou ficar duas semanas.", sentenceA2Pt: "A duração da minha estadia é de aproximadamente quinze dias." },
    { english: "Currency", portuguese: "Moeda / Dinheiro", sentenceA1: "I need to exchange currency.", sentenceA2: "What is the best place to exchange currency near the hotel?", sentenceA1Pt: "Preciso trocar moeda.", sentenceA2Pt: "Qual é o melhor lugar para trocar moeda perto do hotel?" },
    { english: "Customs declaration", portuguese: "Declaração alfandegária", sentenceA1: "I filled out the form.", sentenceA2: "Do I need a customs declaration for personal electronics?", sentenceA1Pt: "Preenchi o formulário.", sentenceA2Pt: "Preciso de declaração alfandegária para eletrônicos pessoais?" },
    { english: "Immigration officer", portuguese: "Oficial de imigração", sentenceA1: "The officer checked my passport.", sentenceA2: "The immigration officer asked me several questions about my trip.", sentenceA1Pt: "O oficial verificou meu passaporte.", sentenceA2Pt: "O oficial de imigração me fez várias perguntas sobre minha viagem." },
    { english: "Tourist visa", portuguese: "Visto de turista", sentenceA1: "I have a tourist visa.", sentenceA2: "My tourist visa allows me to stay for up to ninety days.", sentenceA1Pt: "Tenho um visto de turista.", sentenceA2Pt: "Meu visto de turista permite ficar por até noventa dias." },
    { english: "Return ticket", portuguese: "Passagem de volta", sentenceA1: "Here is my return ticket.", sentenceA2: "The officer asked to see my return ticket.", sentenceA1Pt: "Aqui está minha passagem de volta.", sentenceA2Pt: "O oficial pediu para ver minha passagem de volta." },
    { english: "Fingerprint scanner", portuguese: "Scanner de digital", sentenceA1: "Place your finger here.", sentenceA2: "The fingerprint scanner did not recognize my print at first.", sentenceA1Pt: "Coloque o dedo aqui.", sentenceA2Pt: "O scanner não reconheceu minha digital de primeira." },
    // New ones:
    { english: "Declaring goods", portuguese: "Declaração de mercadorias", sentenceA1: "Do I need to declare this?", sentenceA2: "You have to go to the red channel if you are declaring goods.", sentenceA1Pt: "Preciso declarar isso?", sentenceA2Pt: "Você tem que ir para o canal vermelho se estiver declarando mercadorias." },
    { english: "Business trip", portuguese: "Viagem de negócios", sentenceA1: "I am on a business trip.", sentenceA2: "During my business trip, I have to visit three major clients.", sentenceA1Pt: "Estou em viagem de negócios.", sentenceA2Pt: "Durante minha viagem de negócios, tenho que visitar três clientes importantes." },
    { english: "Green card", portuguese: "Residência permanente", sentenceA1: "He has a green card.", sentenceA2: "She applied for a green card after working in the US for five years.", sentenceA1Pt: "Ele tem green card.", sentenceA2Pt: "Ela solicitou residência permanente após trabalhar nos EUA por cinco anos." },
    { english: "Landed", portuguese: "Pousou / Aterrissou", sentenceA1: "The plane landed.", sentenceA2: "We landed safely at JFK Airport despite the heavy wind.", sentenceA1Pt: "O avião pousou.", sentenceA2Pt: "Pousamos em segurança no aeroporto JFK apesar do vento forte." },
    { english: "Luggage inspection", portuguese: "Inspeção de bagagem", sentenceA1: "They did an inspection.", sentenceA2: "I had to open my suitcase for a random luggage inspection at customs.", sentenceA1Pt: "Eles fizeram uma inspeção.", sentenceA2Pt: "Tive que abrir minha mala para uma inspeção de bagagem aleatória na alfândega." }
  ],
  hotel: [
    { english: "Reservation", portuguese: "Reserva", sentenceA1: "I have a reservation.", sentenceA2: "I made a reservation online for a double room with breakfast.", sentenceA1Pt: "Tenho uma reserva.", sentenceA2Pt: "Fiz uma reserva online para quarto duplo com café da manhã." },
    { english: "Room key", portuguese: "Chave do quarto", sentenceA1: "I lost my room key.", sentenceA2: "The room key stopped working so I went to the front desk.", sentenceA1Pt: "Perdi a chave do quarto.", sentenceA2Pt: "A chave do quarto parou de funcionar e voltei à recepção." },
    { english: "Check-in", portuguese: "Entrada / Check-in", sentenceA1: "I want to check in.", sentenceA2: "What time is check-in? We arrived earlier than expected.", sentenceA1Pt: "Quero fazer o check-in.", sentenceA2Pt: "A que horas é o check-in? Chegamos mais cedo que o esperado." },
    { english: "Check-out", portuguese: "Saída / Check-out", sentenceA1: "I want to check out.", sentenceA2: "Can I get a late check-out until 2 PM?", sentenceA1Pt: "Quero fazer o check-out.", sentenceA2Pt: "Posso fazer check-out tardio até as 14h?" },
    { english: "Lobby", portuguese: "Saguão / Lobby", sentenceA1: "I will wait in the lobby.", sentenceA2: "The hotel lobby has beautiful decorations and comfortable sofas.", sentenceA1Pt: "Vou esperar no lobby.", sentenceA2Pt: "O lobby do hotel tem decorações bonitas e sofás confortáveis." },
    { english: "Elevator", portuguese: "Elevador", sentenceA1: "Where is the elevator?", sentenceA2: "The elevator is out of order so we need to take the stairs.", sentenceA1Pt: "Onde é o elevador?", sentenceA2Pt: "O elevador está fora de serviço e precisamos usar as escadas." },
    { english: "Single room", portuguese: "Quarto individual", sentenceA1: "I need a single room.", sentenceA2: "A single room with a queen bed and city view, please.", sentenceA1Pt: "Preciso de um quarto de solteiro.", sentenceA2Pt: "Um quarto com cama queen e vista para a cidade, por favor." },
    { english: "Towels", portuguese: "Toalhas", sentenceA1: "I need more towels.", sentenceA2: "Could you send extra towels to room 405?", sentenceA1Pt: "Preciso de mais toalhas.", sentenceA2Pt: "Poderia enviar toalhas extras para o quarto 405?" },
    { english: "Front desk", portuguese: "Recepção", sentenceA1: "Ask at the front desk.", sentenceA2: "The front desk is open twenty-four hours.", sentenceA1Pt: "Pergunte na recepção.", sentenceA2Pt: "A recepção fica aberta vinte e quatro horas." },
    { english: "Bellhop", portuguese: "Carregador", sentenceA1: "The bellhop carried my bags.", sentenceA2: "The bellhop helped us with our luggage and showed us the room.", sentenceA1Pt: "O carregador levou minhas malas.", sentenceA2Pt: "O carregador nos ajudou com a bagagem e nos levou ao quarto." },
    { english: "Housekeeping", portuguese: "Arrumação de quarto", sentenceA1: "Call housekeeping, please.", sentenceA2: "Housekeeping comes every morning to clean and make the bed.", sentenceA1Pt: "Chame a arrumação, por favor.", sentenceA2Pt: "A arrumação vem toda manhã para limpar e arrumar a cama." },
    { english: "Room service", portuguese: "Serviço de quarto", sentenceA1: "I want room service.", sentenceA2: "We ordered room service because we were too tired to go out.", sentenceA1Pt: "Quero serviço de quarto.", sentenceA2Pt: "Pedimos serviço de quarto porque estávamos cansados demais." },
    { english: "Deposit", portuguese: "Depósito / Caução", sentenceA1: "Is there a deposit?", sentenceA2: "The hotel requires a two hundred dollar deposit at check-in.", sentenceA1Pt: "Tem um depósito?", sentenceA2Pt: "O hotel exige um depósito de duzentos dólares no check-in." },
    { english: "Pillow", portuguese: "Travesseiro", sentenceA1: "I need an extra pillow.", sentenceA2: "Could you send a softer pillow to my room, please?", sentenceA1Pt: "Preciso de um travesseiro extra.", sentenceA2Pt: "Poderia enviar um travesseiro mais macio para o meu quarto, por favor?" },
    { english: "Blanket", portuguese: "Cobertor", sentenceA1: "It is cold. I need a blanket.", sentenceA2: "Is there an extra blanket in the closet?", sentenceA1Pt: "Está frio. Preciso de um cobertor.", sentenceA2Pt: "Tem um cobertor extra no armário?" },
    { english: "Swimming pool", portuguese: "Piscina", sentenceA1: "Where is the swimming pool?", sentenceA2: "The outdoor swimming pool is open from 8 AM to 10 PM.", sentenceA1Pt: "Onde fica a piscina?", sentenceA2Pt: "A piscina externa fica aberta das 8h às 22h." },
    { english: "Hair dryer", portuguese: "Secador de cabelo", sentenceA1: "Does the bathroom have a hair dryer?", sentenceA2: "The hair dryer in my room is not working properly.", sentenceA1Pt: "O banheiro tem secador de cabelo?", sentenceA2Pt: "O secador de cabelo do meu quarto não está funcionando direito." },
    { english: "Safe", portuguese: "Cofre", sentenceA1: "Where is the room safe?", sentenceA2: "You can keep your passport and valuables in the electronic safe.", sentenceA1Pt: "Onde fica o cofre do quarto?", sentenceA2Pt: "Você pode guardar seu passaporte e objetos de valor no cofre eletrônico." },
    { english: "Double room", portuguese: "Quarto de casal", sentenceA1: "I reserved a double room.", sentenceA2: "A double room with two twin beds is also available.", sentenceA1Pt: "Eu reservei um quarto de casal.", sentenceA2Pt: "Um quarto duplo com duas camas de solteiro também está disponível." },
    // New ones:
    { english: "Luggage storage", portuguese: "Guarda-volumes", sentenceA1: "Can I leave my bags?", sentenceA2: "The hotel offers luggage storage for guests after check-out.", sentenceA1Pt: "Posso deixar minhas malas?", sentenceA2Pt: "O hotel oferece serviço de guarda-volumes para hóspedes após o check-out." },
    { english: "Wake-up call", portuguese: "Serviço de despertar", sentenceA1: "I need a wake-up call.", sentenceA2: "Could you schedule a wake-up call for me tomorrow at 6:30 AM?", sentenceA1Pt: "Preciso de um serviço de despertar.", sentenceA2Pt: "Você poderia programar para me despertarem amanhã às 6h30?" },
    { english: "Air conditioning", portuguese: "Ar condicionado", sentenceA1: "The AC is not cold.", sentenceA2: "Can you send someone to fix the air conditioning in my room?", sentenceA1Pt: "O ar condicionado não gela.", sentenceA2Pt: "Pode mandar alguém consertar o ar condicionado do meu quarto?" }
  ],
  restaurant: [
    { english: "Menu", portuguese: "Cardápio", sentenceA1: "Can I see the menu?", sentenceA2: "The menu has a great variety of local and international dishes.", sentenceA1Pt: "Posso ver o cardápio?", sentenceA2Pt: "O cardápio tem grande variedade de pratos locais e internacionais." },
    { english: "Appetizer", portuguese: "Entrada", sentenceA1: "I want an appetizer.", sentenceA2: "We ordered a cheese appetizer to share while we wait.", sentenceA1Pt: "Quero uma entrada.", sentenceA2Pt: "Pedimos uma entrada de queijo para dividir enquanto esperamos." },
    { english: "Main course", portuguese: "Prato principal", sentenceA1: "The main course is steak.", sentenceA2: "For my main course, I would like the grilled salmon.", sentenceA1Pt: "O prato principal é bife.", sentenceA2Pt: "Para o prato principal, gostaria do salmão grelhado." },
    { english: "Dessert", portuguese: "Sobremesa", sentenceA1: "I want a dessert.", sentenceA2: "The chocolate lava cake is the best dessert on the menu.", sentenceA1Pt: "Quero uma sobremesa.", sentenceA2Pt: "O petit gâteau de chocolate é a melhor sobremesa do cardápio." },
    { english: "Check / Bill", portuguese: "Conta", sentenceA1: "Can I have the check?", sentenceA2: "Could we have the check? We need to leave soon.", sentenceA1Pt: "Pode trazer a conta?", sentenceA2Pt: "Pode trazer a conta? Precisamos sair logo." },
    { english: "Tip", portuguese: "Gorjeta", sentenceA1: "I left a tip.", sentenceA2: "In the US it is common to leave a fifteen to twenty percent tip.", sentenceA1Pt: "Deixei gorjeta.", sentenceA2Pt: "Nos EUA é comum deixar gorjeta de quinze a vinte por cento." },
    { english: "Waiter", portuguese: "Garçom", sentenceA1: "The waiter is very nice.", sentenceA2: "The waiter recommended the fish and it was excellent.", sentenceA1Pt: "O garçom é muito gentil.", sentenceA2Pt: "O garçom recomendou o peixe e foi excelente." },
    { english: "To go", portuguese: "Para levar", sentenceA1: "I want this to go.", sentenceA2: "Can I get a box? I could not finish my meal.", sentenceA1Pt: "Quero isso para levar.", sentenceA2Pt: "Posso pegar uma caixa? Não consegui terminar a refeição." },
    { english: "Napkin", portuguese: "Guardanapo", sentenceA1: "I need a napkin.", sentenceA2: "Could you bring some extra napkins to our table?", sentenceA1Pt: "Preciso de um guardanapo.", sentenceA2Pt: "Poderia trazer guardanapos extras para nossa mesa?" },
    { english: "Fork", portuguese: "Garfo", sentenceA1: "I need a fork.", sentenceA2: "I dropped my fork. Could I have a clean one?", sentenceA1Pt: "Preciso de um garfo.", sentenceA2Pt: "Derrubei meu garfo. Poderia me dar um limpo?" },
    { english: "Knife", portuguese: "Faca", sentenceA1: "I need a knife.", sentenceA2: "This steak is tough. Do you have a sharper knife?", sentenceA1Pt: "Preciso de uma faca.", sentenceA2Pt: "Este bife está duro. Tem uma faca mais afiada?" },
    { english: "Spoon", portuguese: "Colher", sentenceA1: "I need a spoon.", sentenceA2: "She asked for a small spoon to stir her coffee.", sentenceA1Pt: "Preciso de uma colher.", sentenceA2Pt: "Ela pediu uma colher pequena para mexer o café." },
    { english: "Tap water", portuguese: "Água da torneira", sentenceA1: "Can I have tap water?", sentenceA2: "In many countries, tap water is safe to drink.", sentenceA1Pt: "Posso ter água da torneira?", sentenceA2Pt: "Em muitos países, a água da torneira é segura para beber." },
    { english: "Spicy", portuguese: "Apimentado", sentenceA1: "This is very spicy!", sentenceA2: "I love spicy food, but this dish is too hot for me.", sentenceA1Pt: "Isso é muito apimentado!", sentenceA2Pt: "Adoro comida apimentada, mas esse prato é demais para mim." },
    { english: "Vegetarian", portuguese: "Vegetariano", sentenceA1: "I am vegetarian.", sentenceA2: "Do you have any vegetarian options on the menu?", sentenceA1Pt: "Sou vegetariano(a).", sentenceA2Pt: "Vocês têm opções vegetarianas no cardápio?" },
    // New ones:
    { english: "Allergy", portuguese: "Alergia", sentenceA1: "I have a peanut allergy.", sentence2: "Please let the chef know about my gluten allergy.", sentenceA1: "Tenho alergia a amendoim.", sentenceA2: "Por favor, avise o chef sobre a minha alergia a glúten.", sentenceA1Pt: "Tenho alergia a amendoim.", sentenceA2Pt: "Por favor, avise o chef sobre a minha alergia a glúten." },
    { english: "Side dish", portuguese: "Acompanhamento", sentenceA1: "What side dish comes with it?", sentenceA2: "I ordered french fries as a side dish for my hamburger.", sentenceA1Pt: "Qual acompanhamento vem?", sentenceA2Pt: "Pedi batatas fritas como acompanhamento para o meu hambúrguer." },
    { english: "Still water / Sparkling water", portuguese: "Água sem gás / Água com gás", sentenceA1: "Sparkling water, please.", sentenceA2: "Would you like still water or sparkling water with your meal?", sentenceA1Pt: "Água com gás, por favor.", sentenceA2Pt: "Você gostaria de água sem gás ou com gás com a refeição?" },
    { english: "Medium rare", portuguese: "Ao ponto para mal passada", sentenceA1: "I want my steak medium rare.", sentenceA2: "He prefers his meat medium rare, so please don't overcook it.", sentenceA1Pt: "Quero meu bife ao ponto para mal passado.", sentenceA2Pt: "Ele prefere a carne ao ponto para mal passada, então por favor não passe do ponto." },
    { english: "Soft drink", portuguese: "Refrigerante", sentenceA1: "I want a soft drink.", sentenceA2: "Do you have any sugar-free soft drinks available?", sentenceA1Pt: "Quero um refrigerante.", sentenceA2Pt: "Você tem algum refrigerante sem açúcar disponível?" }
  ],
  directions: [
    { english: "Turn left", portuguese: "Vire à esquerda", sentenceA1: "Turn left at the corner.", sentenceA2: "Turn left after the traffic light and walk two more blocks.", sentenceA1Pt: "Vire à esquerda na esquina.", sentenceA2Pt: "Vire à esquerda depois do semáforo e ande mais dois quarteirões." },
    { english: "Turn right", portuguese: "Vire à direita", sentenceA1: "Turn right here.", sentenceA2: "Turn right at the next intersection and you will see the bank.", sentenceA1Pt: "Vire à direita aqui.", sentenceA2Pt: "Vire à direita na próxima interseção e verá o banco." },
    { english: "Go straight", portuguese: "Siga em frente", sentenceA1: "Go straight two blocks.", sentenceA2: "Go straight for five minutes and the museum is on your left.", sentenceA1Pt: "Siga em frente dois quarteirões.", sentenceA2Pt: "Siga em frente por cinco minutos e o museu fica à sua esquerda." },
    { english: "Block", portuguese: "Quarteirão / Bloco", sentenceA1: "It is two blocks away.", sentenceA2: "The pharmacy is about three blocks from here.", sentenceA1Pt: "Fica a dois quarteirões.", sentenceA2Pt: "A farmácia fica a três quarteirões daqui." },
    { english: "Corner", portuguese: "Esquina", sentenceA1: "It is on the corner.", sentenceA2: "There is a great coffee shop on the corner of Fifth Avenue.", sentenceA1Pt: "Fica na esquina.", sentenceA2Pt: "Tem uma ótima cafeteria na esquina da Quinta Avenida." },
    { english: "Cross the street", portuguese: "Atravessar a rua", sentenceA1: "Cross the street here.", sentenceA2: "Cross the street at the crosswalk and the store is right there.", sentenceA1Pt: "Atravesse a rua aqui.", sentenceA2Pt: "Atravesse na faixa de pedestres e a loja fica ali." },
    { english: "Traffic light", portuguese: "Semáforo", sentenceA1: "Stop at the traffic light.", sentenceA2: "Wait for the traffic light to turn green before you cross.", sentenceA1Pt: "Pare no semáforo.", sentenceA2Pt: "Espere o semáforo ficar verde antes de atravessar." },
    { english: "Sidewalk", portuguese: "Calçada", sentenceA1: "Walk on the sidewalk.", sentenceA2: "The sidewalk is very wide here so it is easy to walk.", sentenceA1Pt: "Ande na calçada.", sentenceA2Pt: "A calçada aqui é bem larga então é fácil andar." },
    { english: "Crosswalk", portuguese: "Faixa de pedestres", sentenceA1: "Use the crosswalk.", sentenceA2: "Always use the crosswalk to cross the street safely.", sentenceA1Pt: "Use a faixa de pedestres.", sentenceA2Pt: "Sempre use a faixa de pedestres para atravessar com segurança." },
    { english: "Intersection", portuguese: "Interseção / Cruzamento", sentenceA1: "It is at the intersection.", sentenceA2: "The accident happened at the intersection of Main and Oak.", sentenceA1Pt: "Fica na interseção.", sentenceA2Pt: "O acidente aconteceu na interseção da Main com a Oak." },
    { english: "Across from", portuguese: "Em frente a", sentenceA1: "It is across from the park.", sentenceA2: "The restaurant is directly across from the movie theater.", sentenceA1Pt: "Fica em frente ao parque.", sentenceA2Pt: "O restaurante fica em frente ao cinema." },
    { english: "Next to", portuguese: "Ao lado de", sentenceA1: "It is next to the bank.", sentenceA2: "The post office is next to the pharmacy on the main street.", sentenceA1Pt: "Fica ao lado do banco.", sentenceA2Pt: "O correio fica ao lado da farmácia na rua principal." },
    { english: "Downtown", portuguese: "Centro da cidade", sentenceA1: "I am going downtown.", sentenceA2: "Downtown is always crowded on weekends because of the shops.", sentenceA1Pt: "Estou indo ao centro.", sentenceA2Pt: "O centro está sempre lotado nos fins de semana por causa das lojas." },
    // New ones:
    { english: "Lost", portuguese: "Perdido(a)", sentenceA1: "Help me, I am lost.", sentenceA2: "I got lost in the subway station because it has too many exits.", sentenceA1Pt: "Ajude-me, estou perdido.", sentenceA2Pt: "Eu me perdi na estação de metrô porque ela tem saídas demais." },
    { english: "Map", portuguese: "Mapa", sentenceA1: "Look at the map.", sentence2: "Can you show me our current location on this paper map?", sentenceA1: "Olhe no mapa.", sentenceA2: "Você pode me mostrar nossa localização atual neste mapa de papel?", sentenceA1Pt: "Olhe no mapa.", sentenceA2Pt: "Você pode me mostrar nossa localização atual neste mapa de papel?" },
    { english: "Behind", portuguese: "Atrás de", sentenceA1: "It is behind the hotel.", sentenceA2: "The parking lot is located right behind the main building.", sentenceA1Pt: "Fica atrás do hotel.", sentenceA2Pt: "O estacionamento fica localizado bem atrás do prédio principal." },
    { english: "Far", portuguese: "Longe", sentenceA1: "Is the station far?", sentenceA2: "The airport is quite far from here, you should take a highway.", sentenceA1Pt: "A estação é longe?", sentenceA2Pt: "O aeroporto é bastante longe daqui, você deveria pegar a rodovia." },
    { english: "Nearby", portuguese: "Perto / Próximo", sentenceA1: "Is there a café nearby?", sentenceA2: "There are several good restaurants nearby within walking distance.", sentenceA1Pt: "Tem alguma cafeteria perto?", sentenceA2Pt: "Há vários bons restaurantes próximos a uma curta caminhada de distância." }
  ],
  transport: [
    { english: "Ride", portuguese: "Carona / Corrida", sentenceA1: "I need a ride.", sentenceA2: "Can you give me a ride to the airport tomorrow?", sentenceA1Pt: "Preciso de uma carona.", sentenceA2Pt: "Pode me dar uma carona ao aeroporto amanhã?" },
    { english: "Fare", portuguese: "Tarifa / Preço da passagem", sentenceA1: "How much is the fare?", sentenceA2: "The bus fare increased by ten percent last month.", sentenceA1Pt: "Quanto é a tarifa?", sentenceA2Pt: "A tarifa do ônibus aumentou dez por cento mês passado." },
    { english: "Driver", portuguese: "Motorista", sentenceA1: "The driver is nice.", sentenceA2: "The taxi driver took the fastest route to avoid traffic.", sentenceA1Pt: "O motorista é gentil.", sentenceA2Pt: "O taxista pegou a rota mais rápida para evitar trânsito." },
    { english: "Subway / Metro", portuguese: "Metrô", sentenceA1: "I take the subway every day.", sentenceA2: "The subway is the fastest way to get around during rush hour.", sentenceA1Pt: "Pego o metrô todo dia.", sentenceA2Pt: "O metrô é a forma mais rápida de se locomover na hora do rush." },
    { english: "Platform", portuguese: "Plataforma", sentenceA1: "Wait on platform 3.", sentenceA2: "The train to the airport departs from platform 5.", sentenceA1Pt: "Espere na plataforma 3.", sentenceA2Pt: "O trem para o aeroporto sai da plataforma 5." },
    { english: "Transfer", portuguese: "Baldeação / Conexão", sentenceA1: "I need to transfer here.", sentenceA2: "You need to transfer at the next station to the blue line.", sentenceA1Pt: "Preciso fazer baldeação aqui.", sentenceA2Pt: "Precisa fazer baldeação na próxima estação para a linha azul." },
    { english: "Stop", portuguese: "Parada / Ponto", sentenceA1: "The next stop is mine.", sentenceA2: "Could you tell me when we reach the stop near the hospital?", sentenceA1Pt: "A próxima parada é a minha.", sentenceA2Pt: "Pode me avisar quando chegarmos na parada perto do hospital?" },
    { english: "Metro card", portuguese: "Cartão do metrô", sentenceA1: "I need a metro card.", sentenceA2: "You can recharge your metro card at any station.", sentenceA1Pt: "Preciso de um cartão de metrô.", sentenceA2Pt: "Pode recarregar seu cartão em qualquer estação." },
    { english: "Rush hour", portuguese: "Hora do rush", sentenceA1: "It is rush hour now.", sentenceA2: "I avoid traveling during rush hour because the trains are packed.", sentenceA1Pt: "É hora do rush agora.", sentenceA2Pt: "Evito viajar na hora do rush porque os trens ficam lotados." },
    { english: "Passenger", portuguese: "Passageiro", sentenceA1: "I am a passenger.", sentenceA2: "The bus was full of passengers going to work.", sentenceA1Pt: "Sou um passageiro.", sentenceA2Pt: "O ônibus estava cheio de passageiros indo trabalhar." },
    { english: "Ticket", portuguese: "Passagem / Bilhete", sentenceA1: "I bought a ticket.", sentenceA2: "A round-trip ticket is cheaper than two one-way tickets.", sentenceA1Pt: "Comprei uma passagem.", sentenceA2Pt: "Uma passagem de ida e volta é mais barata que duas de ida." },
    { english: "To get on", portuguese: "Embarcar / Subir", sentenceA1: "I get on the bus here.", sentenceA2: "We need to get on the next train or we will be late.", sentenceA1Pt: "Pego o ônibus aqui.", sentenceA2Pt: "Precisamos pegar o próximo trem ou vamos nos atrasar." },
    { english: "To get off", portuguese: "Desembarcar / Descer", sentenceA1: "I get off at the next stop.", sentenceA2: "Remember to get off at Central Station for the museum.", sentenceA1Pt: "Desço na próxima parada.", sentenceA2Pt: "Lembre-se de descer na Estação Central para o museu." },
    { english: "Traffic jam", portuguese: "Engarrafamento", sentenceA1: "There is a traffic jam.", sentenceA2: "We were stuck in a traffic jam for over an hour.", sentenceA1Pt: "Tem um engarrafamento.", sentenceA2Pt: "Ficamos presos em um engarrafamento por mais de uma hora." },
    // New ones:
    { english: "One-way ticket", portuguese: "Passagem de ida", sentenceA1: "I need a one-way ticket.", sentenceA2: "Buying a one-way ticket is more expensive than buying a round-trip one.", sentenceA1Pt: "Preciso de uma passagem de ida.", sentenceA2Pt: "Comprar uma passagem só de ida é mais caro do que comprar uma de ida e volta." },
    { english: "Round-trip ticket", portuguese: "Passagem de ida e volta", sentenceA1: "A round-trip ticket, please.", sentenceA2: "The round-trip ticket costs eighty dollars and is valid for a month.", sentenceA1Pt: "Passagem de ida e volta, por favor.", sentenceA2Pt: "A passagem de ida e volta custa oitenta dólares e é válida por um mês." },
    { english: "Schedule / Timetable", portuguese: "Cronograma / Horários", sentenceA1: "Where is the train schedule?", sentenceA2: "You should check the bus timetable online to see the frequency.", sentenceA1Pt: "Onde está o horário dos trens?", sentenceA2Pt: "Você deveria verificar os horários de ônibus online para ver a frequência." },
    { english: "Delay", portuguese: "Atraso", sentenceA1: "Is there a delay?", sentenceA2: "There is a twenty-minute delay on the red line due to mechanical issues.", sentenceA1Pt: "Tem algum atraso?", sentenceA2Pt: "Há um atraso de vinte minutos na linha vermelha devido a problemas mecânicos." }
  ],
  medical: [
    { english: "Headache", portuguese: "Dor de cabeça", sentenceA1: "I have a headache.", sentenceA2: "I have had a terrible headache since yesterday.", sentenceA1Pt: "Estou com dor de cabeça.", sentenceA2Pt: "Estou com uma dor de cabeça terrível desde ontem." },
    { english: "Sore throat", portuguese: "Dor de garganta", sentenceA1: "I have a sore throat.", sentenceA2: "My sore throat makes it difficult to swallow food.", sentenceA1Pt: "Estou com dor de garganta.", sentenceA2Pt: "Minha dor de garganta dificulta engolir comida." },
    { english: "Fever", portuguese: "Febre", sentenceA1: "I have a fever.", sentenceA2: "The doctor said I have a mild fever and should rest.", sentenceA1Pt: "Estou com febre.", sentenceA2Pt: "O médico disse que estou com febre leve e devo descansar." },
    { english: "Pain reliever", portuguese: "Analgésico", sentenceA1: "I need a pain reliever.", sentenceA2: "Can you recommend a good pain reliever for muscle pain?", sentenceA1Pt: "Preciso de um analgésico.", sentenceA2Pt: "Pode recomendar um bom analgésico para dor muscular?" },
    { english: "Emergency", portuguese: "Emergência", sentenceA1: "This is an emergency!", sentenceA2: "Call an ambulance! This is a medical emergency.", sentenceA1Pt: "Isto é uma emergência!", sentenceA2Pt: "Chame uma ambulância! Isto é uma emergência médica." },
    { english: "Appointment", portuguese: "Consulta médica", sentenceA1: "I have a doctor appointment.", sentenceA2: "I need to schedule an appointment with a specialist.", sentenceA1Pt: "Tenho uma consulta médica.", sentenceA2Pt: "Preciso marcar consulta com um especialista." },
    { english: "Prescription", portuguese: "Receita médica", sentenceA1: "I have a prescription.", sentenceA2: "The doctor wrote a prescription for antibiotics.", sentenceA1Pt: "Tenho uma receita.", sentenceA2Pt: "O médico passou uma receita de antibióticos." },
    { english: "Insurance", portuguese: "Plano de saúde", sentenceA1: "I have health insurance.", sentenceA2: "My insurance covers most of the costs for check-ups.", sentenceA1Pt: "Tenho plano de saúde.", sentenceA2Pt: "Meu plano cobre a maior parte dos custos de check-ups." },
    { english: "Insurance card", portuguese: "Cartão do plano", sentenceA1: "Here is my insurance card.", sentenceA2: "Please bring your insurance card and photo ID.", sentenceA1Pt: "Aqui está meu cartão do plano.", sentenceA2Pt: "Traga seu cartão do plano e identidade com foto." },
    { english: "Symptoms", portuguese: "Sintomas", sentenceA1: "What are your symptoms?", sentenceA2: "My symptoms started three days ago with a cough.", sentenceA1Pt: "Quais são seus sintomas?", sentenceA2Pt: "Meus sintomas começaram três dias atrás com tosse." },
    { english: "Pain", portuguese: "Dor", sentenceA1: "I feel pain here.", sentenceA2: "The pain in my back gets worse when I sit too long.", sentenceA1Pt: "Sinto dor aqui.", sentenceA2Pt: "A dor nas costas piora quando fico sentado muito tempo." },
    { english: "Bandage", portuguese: "Curativo / Bandagem", sentenceA1: "I need a bandage.", sentenceA2: "The nurse put a clean bandage on my cut.", sentenceA1Pt: "Preciso de uma bandagem.", sentenceA2Pt: "A enfermeira colocou uma bandagem limpa no meu corte." },
    { english: "Cough", portuguese: "Tosse", sentenceA1: "I have a bad cough.", sentenceA2: "My cough keeps me awake at night.", sentenceA1Pt: "Estou com tosse forte.", sentenceA2Pt: "Minha tosse me mantém acordado à noite." },
    { english: "Cold", portuguese: "Resfriado", sentenceA1: "I have a cold.", sentenceA2: "I caught a cold last week and I am still recovering.", sentenceA1Pt: "Estou resfriado(a).", sentenceA2Pt: "Peguei um resfriado semana passada e ainda estou me recuperando." },
    // New ones:
    { english: "Pharmacy / Drugstore", portuguese: "Farmácia", sentenceA1: "Where is the pharmacy?", sentenceA2: "You can buy over-the-counter medicine at the local drugstore.", sentenceA1Pt: "Onde fica a farmácia?", sentenceA2Pt: "Você pode comprar medicamentos sem receita na farmácia local." },
    { english: "Pills / Tablets", portuguese: "Pílulas / Comprimidos", sentenceA1: "Take two pills.", sentenceA2: "The doctor told me to take these pills with meals twice a day.", sentenceA1Pt: "Tome duas pílulas.", sentenceA2Pt: "O médico me disse para tomar essas pílulas com as refeições duas vezes ao dia." },
    { english: "Side effects", portuguese: "Efeitos colaterais", sentenceA1: "Are there side effects?", sentenceA2: "This medicine may cause mild side effects like drowsiness.", sentenceA1Pt: "Tem efeitos colaterais?", sentenceA2Pt: "Este medicamento pode causar efeitos colaterais leves, como sonolência." },
    { english: "Ointment", portuguese: "Pomada", sentenceA1: "Apply the ointment.", sentenceA2: "You should apply this ointment to the skin allergy twice a day.", sentenceA1Pt: "Aplique a pomada.", sentenceA2Pt: "Você deve aplicar esta pomada na alergia cutânea duas vezes ao dia." }
  ],
  entertainment: [
    { english: "Tickets", portuguese: "Ingressos", sentenceA1: "I bought two tickets.", sentenceA2: "I bought the tickets online because they were cheaper.", sentenceA1Pt: "Comprei dois ingressos.", sentenceA2Pt: "Comprei os ingressos online porque eram mais baratos." },
    { english: "Show", portuguese: "Apresentação / Show", sentenceA1: "The show starts at 8 PM.", sentenceA2: "The comedy show last night was amazing.", sentenceA1Pt: "O show começa às 20h.", sentenceA2Pt: "O show de comédia ontem à noite foi incrível." },
    { english: "Box office", portuguese: "Bilheteria", sentenceA1: "The box office is closed.", sentenceA2: "You can buy tickets at the box office or online.", sentenceA1Pt: "A bilheteria está fechada.", sentenceA2Pt: "Pode comprar ingressos na bilheteria ou online." },
    { english: "Recommendation", portuguese: "Recomendação", sentenceA1: "Do you have a recommendation?", sentenceA2: "The staff gave me a great recommendation for a jazz club.", sentenceA1Pt: "Tem uma recomendação?", sentenceA2Pt: "A equipe me deu uma ótima recomendação de um clube de jazz." },
    { english: "Sold out", portuguese: "Esgotado", sentenceA1: "The show is sold out.", sentenceA2: "All the good seats are sold out.", sentenceA1Pt: "O show está esgotado.", sentenceA2Pt: "Todos os bons lugares estão esgotados." },
    { english: "Entrance", portuguese: "Entrada", sentenceA1: "Where is the entrance?", sentenceA2: "The main entrance is on the left side of the building.", sentenceA1Pt: "Onde é a entrada?", sentenceA2Pt: "A entrada principal fica do lado esquerdo do prédio." },
    { english: "Performance", portuguese: "Performance / Show", sentenceA1: "The performance was great.", sentenceA2: "The ballet performance was breathtaking.", sentenceA1Pt: "A apresentação foi ótima.", sentenceA2Pt: "A apresentação de balé foi espetacular." },
    { english: "Souvenir", portuguese: "Lembrança / Souvenir", sentenceA1: "I bought a souvenir.", sentenceA2: "I always buy a souvenir from every city I visit.", sentenceA1Pt: "Comprei uma lembrança.", sentenceA2Pt: "Sempre compro uma lembrança de cada cidade que visito." },
    { english: "Row", portuguese: "Fileira", sentenceA1: "We are in row five.", sentenceA2: "Our seats are in row ten, right in the center.", sentenceA1Pt: "Estamos na fileira cinco.", sentenceA2Pt: "Nossos assentos ficam na fileira dez, no centro." },
    { english: "Stage", portuguese: "Palco", sentenceA1: "The stage is very big.", sentenceA2: "The singer walked across the entire stage.", sentenceA1Pt: "O palco é muito grande.", sentenceA2Pt: "A cantora andou por todo o palco." },
    { english: "Main entrance", portuguese: "Entrada principal", sentenceA1: "Go to the main entrance.", sentence2: "Meet me at the main entrance thirty minutes before the show.", sentenceA1: "Vá para a entrada principal.", sentenceA2: "Encontre-me na entrada principal trinta minutos antes do show.", sentenceA1Pt: "Vá para a entrada principal.", sentenceA2Pt: "Encontre-me na entrada principal trinta minutos antes do show." },
    { english: "Restroom", portuguese: "Banheiro", sentenceA1: "Where is the restroom?", sentenceA2: "The restrooms are on the second floor near the elevator.", sentenceA1Pt: "Onde é o banheiro?", sentenceA2Pt: "Os banheiros ficam no segundo andar perto do elevador." },
    { english: "Coat check", portuguese: "Guarda-volumes", sentenceA1: "Is there a coat check?", sentenceA2: "You can leave your jacket at the coat check near the entrance.", sentenceA1Pt: "Tem um guarda-volumes?", sentenceA2Pt: "Pode deixar sua jaqueta no guarda-volumes perto da entrada." },
    // New ones:
    { english: "Concert", portuguese: "Show / Concerto", sentenceA1: "I am going to a concert.", sentenceA2: "The outdoor concert was canceled because of the storm warning.", sentenceA1Pt: "Vou a um show.", sentenceA2Pt: "O show ao ar livre foi cancelado devido ao alerta de tempestade." },
    { english: "Seat number", portuguese: "Número do assento", sentenceA1: "My seat number is 14.", sentenceA2: "Please check your ticket to find your exact seat number.", sentenceA1Pt: "Meu assento é o 14.", sentenceA2Pt: "Por favor, verifique sua passagem para encontrar o número exato do seu assento." },
    { english: "Schedule", portuguese: "Programação / Horário", sentenceA1: "Where is the show schedule?", sentenceA2: "The theater schedule lists all the plays and times for this month.", sentenceA1Pt: "Onde está a programação?", sentenceA2Pt: "A programação do teatro lista todas as peças e horários para este mês." },
    { english: "Opening act", portuguese: "Show de abertura", sentenceA1: "Who is the opening act?", sentenceA2: "The opening act started playing at 7:30 PM, before the main band.", sentenceA1Pt: "Quem é a abertura?", sentenceA2Pt: "O show de abertura começou às 19h30, antes da banda principal." }
  ],
  cafe: [
    { english: "Tall / Grande / Venti", portuguese: "Tamanhos de copo", sentenceA1: "I want a tall coffee.", sentenceA2: "Can I have a grande iced latte with extra espresso?", sentenceA1Pt: "Quero um café pequeno.", sentenceA2Pt: "Posso pedir um latte gelado médio com espresso extra?" },
    { english: "Whole milk", portuguese: "Leite integral", sentenceA1: "With whole milk, please.", sentenceA2: "I prefer whole milk because it makes my cappuccino creamier.", sentenceA1Pt: "Com leite integral, por favor.", sentenceA2Pt: "Prefiro leite integral porque fica mais cremoso." },
    { english: "Oat milk", portuguese: "Leite de aveia", sentenceA1: "I want oat milk.", sentenceA2: "Could you replace the regular milk with oat milk?", sentenceA1Pt: "Quero leite de aveia.", sentenceA2Pt: "Pode trocar o leite normal por leite de aveia?" },
    { english: "Decaf", portuguese: "Descafeinado", sentenceA1: "I want decaf coffee.", sentenceA2: "I switched to decaf because coffee was keeping me awake.", sentenceA1Pt: "Quero café descafeinado.", sentenceA2Pt: "Mudei para descafeinado porque o café me mantinha acordado." },
    { english: "Whipped cream", portuguese: "Chantilly", sentenceA1: "With whipped cream, please.", sentenceA2: "Can I add extra whipped cream on my hot chocolate?", sentenceA1Pt: "Com chantilly, por favor.", sentenceA2Pt: "Posso adicionar chantilly extra no meu chocolate quente?" },
    { english: "Drive-thru", portuguese: "Drive-thru", sentenceA1: "Let us go to the drive-thru.", sentenceA2: "The drive-thru line is always long in the morning.", sentenceA1Pt: "Vamos ao drive-thru.", sentenceA2Pt: "A fila do drive-thru é sempre longa de manhã." },
    { english: "For here / To go", portuguese: "Para consumir aqui / Para levar", sentenceA1: "For here, please.", sentenceA2: "Is this for here or to go? I will have it to go.", sentenceA1Pt: "Para consumir aqui, por favor.", sentenceA2Pt: "É para aqui ou para levar? Hoje vou levar." },
    { english: "Combo / Meal", portuguese: "Combo", sentenceA1: "I want the combo.", sentenceA2: "The breakfast combo includes coffee, a sandwich, and a cookie.", sentenceA1Pt: "Quero o combo.", sentenceA2Pt: "O combo inclui café, sanduíche e biscoito." },
    { english: "Napkin", portuguese: "Guardanapo", sentenceA1: "I need a napkin.", sentenceA2: "Could you give me extra napkins? My coffee spilled.", sentenceA1Pt: "Preciso de um guardanapo.", sentenceA2Pt: "Pode me dar guardanapos extras? Meu café derramou." },
    { english: "Straw", portuguese: "Canudo", sentenceA1: "I need a straw.", sentenceA2: "They only offer paper straws now for the environment.", sentenceA1Pt: "Preciso de um canudo.", sentenceA2Pt: "Eles só oferecem canudos de papel agora pelo meio ambiente." },
    { english: "Sugar packet", portuguese: "Pacote de açúcar", sentenceA1: "I need a sugar packet.", sentenceA2: "Could you pass me two sugar packets and a stirrer?", sentenceA1Pt: "Preciso de açúcar.", sentenceA2Pt: "Pode me passar dois açúcares e um mexedor?" },
    { english: "To go bag", portuguese: "Sacola para levar", sentenceA1: "Can I have a bag?", sentenceA2: "Put the pastries in a bag. I will eat them at the office.", sentenceA1Pt: "Posso ter uma sacola?", sentenceA2Pt: "Coloque os doces em uma sacola. Vou comer no escritório." },
    { english: "Extra hot", portuguese: "Muito quente", sentenceA1: "Extra hot, please.", sentenceA2: "I like my latte extra hot because it stays warm longer.", sentenceA1Pt: "Bem quente, por favor.", sentenceA2Pt: "Gosto do meu latte bem quente porque dura mais." },
    // New ones:
    { english: "Pastry", portuguese: "Folhado / Doce / Salgado", sentenceA1: "I want a sweet pastry.", sentenceA2: "They serve fresh pastries like croissants and muffins every morning.", sentenceA1Pt: "Quero um doce folhado.", sentenceA2Pt: "Eles servem salgados e doces frescos como croissants e muffins todas as manhãs." },
    { english: "Espresso shot", portuguese: "Dose de espresso", sentenceA1: "Add a shot of espresso.", sentenceA2: "I need a double shot of espresso to wake up today.", sentenceA1Pt: "Adicione uma dose de espresso.", sentenceA2Pt: "Preciso de uma dose dupla de espresso para acordar hoje." },
    { english: "Sweetener", portuguese: "Adoçante", sentenceA1: "Do you have sweetener?", sentenceA2: "I prefer to use sweetener instead of sugar in my coffee.", sentenceA1Pt: "Você tem adoçante?", sentenceA2Pt: "Prefiro usar adoçante em vez de açúcar no meu café." },
    { english: "Iced coffee", portuguese: "Café gelado", sentenceA1: "An iced coffee, please.", sentenceA2: "I always order an iced coffee when the weather gets warm.", sentenceA1Pt: "Um café gelado, por favor.", sentenceA2Pt: "Eu sempre peço um café gelado quando o tempo esquenta." }
  ],
  tech: [
    { english: "Network", portuguese: "Rede", sentenceA1: "I have no network.", sentenceA2: "The network coverage is very poor in this area.", sentenceA1Pt: "Estou sem rede.", sentenceA2Pt: "A cobertura de rede é muito fraca nesta área." },
    { english: "Password", portuguese: "Senha", sentenceA1: "What is the password?", sentenceA2: "I changed my password because someone tried to access my account.", sentenceA1Pt: "Qual é a senha?", sentenceA2Pt: "Mudei minha senha porque alguém tentou acessar minha conta." },
    { english: "SIM card / Chip", portuguese: "Chip de celular", sentenceA1: "I need a SIM card.", sentenceA2: "I bought a local SIM card at the airport to avoid roaming.", sentenceA1Pt: "Preciso de um chip.", sentenceA2Pt: "Comprei um chip local no aeroporto para evitar roaming." },
    { english: "Prepaid", portuguese: "Pré-pago", sentenceA1: "I want a prepaid plan.", sentenceA2: "The prepaid plan includes five gigabytes of data.", sentenceA1Pt: "Quero um plano pré-pago.", sentenceA2Pt: "O plano pré-pago inclui cinco gigabytes de dados." },
    { english: "Data plan", portuguese: "Plano de dados", sentenceA1: "I need a data plan.", sentenceA2: "My data plan ran out so I cannot use the internet.", sentenceA1Pt: "Preciso de um plano de dados.", sentenceA2Pt: "Meu plano de dados acabou e não consigo usar a internet." },
    { english: "Coverage", portuguese: "Cobertura", sentenceA1: "Is there coverage here?", sentenceA2: "The coverage is excellent in the city center.", sentenceA1Pt: "Tem cobertura aqui?", sentenceA2Pt: "A cobertura é excelente no centro da cidade." },
    { english: "Unlimited", portuguese: "Ilimitado", sentenceA1: "I want unlimited data.", sentenceA2: "The unlimited plan is worth it if you stream a lot.", sentenceA1Pt: "Quero dados ilimitados.", sentenceA2Pt: "O plano ilimitado vale a pena se você assiste muitos vídeos." },
    { english: "Charger", portuguese: "Carregador", sentenceA1: "I need a charger.", sentenceA2: "I forgot my charger and my battery is at five percent.", sentenceA1Pt: "Preciso de um carregador.", sentenceA2Pt: "Esqueci meu carregador e a bateria está em cinco por cento." },
    { english: "Plug / Outlet", portuguese: "Tomada", sentenceA1: "Where is the outlet?", sentenceA2: "The outlet here uses a different plug so I need an adapter.", sentenceA1Pt: "Onde fica a tomada?", sentenceA2Pt: "A tomada aqui usa um plugue diferente, preciso de um adaptador." },
    { english: "Power bank", portuguese: "Carregador portátil", sentenceA1: "I have a power bank.", sentenceA2: "I always carry a power bank when I travel.", sentenceA1Pt: "Tenho um carregador portátil.", sentenceA2Pt: "Sempre levo um carregador portátil quando viajo." },
    { english: "To charge", portuguese: "Carregar", sentenceA1: "I need to charge my phone.", sentenceA2: "Can I charge my phone here? The battery is almost dead.", sentenceA1Pt: "Preciso carregar meu celular.", sentenceA2Pt: "Posso carregar meu celular aqui? A bateria está quase acabando." },
    { english: "Free Wi-Fi", portuguese: "Wi-Fi gratuito", sentenceA1: "Is there free Wi-Fi?", sentenceA2: "This cafe has free Wi-Fi but you need the password.", sentenceA1Pt: "Tem Wi-Fi grátis?", sentenceA2Pt: "Este café tem Wi-Fi grátis mas você precisa da senha." },
    { english: "No signal", portuguese: "Sem sinal", sentenceA1: "I have no signal.", sentenceA2: "There is no signal in the elevator so I will call you back.", sentenceA1Pt: "Estou sem sinal.", sentenceA2Pt: "Não tem sinal no elevador, vou te ligar de volta." },
    // New ones:
    { english: "Hotspot", portuguese: "Roteador / Compartilhar internet", sentenceA1: "Turn on your hotspot.", sentenceA2: "I used my phone as a mobile hotspot so my laptop could connect.", sentenceA1Pt: "Ligue o seu roteador.", sentenceA2Pt: "Usei meu celular como roteador portátil para meu notebook se conectar." },
    { english: "To download", portuguese: "Baixar / Fazer download", sentenceA1: "Download the app.", sentenceA2: "You should download the offline map before you start hiking.", sentenceA1Pt: "Baixe o aplicativo.", sentenceA2Pt: "Você deveria baixar o mapa offline antes de começar a caminhar." },
    { english: "App / Application", portuguese: "Aplicativo", sentenceA1: "This app is very useful.", sentenceA2: "The airline app allows you to track your luggage in real time.", sentenceA1Pt: "Este aplicativo é muito útil.", sentenceA2Pt: "O app da companhia aérea permite rastrear sua bagagem em tempo real." },
    { english: "Adapter", portuguese: "Adaptador", sentenceA1: "I need an adapter.", sentenceA2: "You will need a universal adapter to plug in your electronics abroad.", sentenceA1Pt: "Preciso de um adaptador.", sentenceA2Pt: "Você precisará de um adaptador universal para ligar seus eletrônicos no exterior." }
  ],
  smalltalk: [
    { english: "Small talk", portuguese: "Conversa informal", sentenceA1: "I like small talk.", sentenceA2: "Making small talk is a great way to practice English.", sentenceA1Pt: "Gosto de conversa informal.", sentenceA2Pt: "Conversa informal é ótima para praticar inglês." },
    { english: "Fingers crossed", portuguese: "Dedos cruzados / Torcendo", sentenceA1: "Fingers crossed!", sentenceA2: "I have a job interview tomorrow. Fingers crossed!", sentenceA1Pt: "Estou torcendo!", sentenceA2Pt: "Tenho uma entrevista amanhã. Estou torcendo!" },
    { english: "Catch the game", portuguese: "Assistir o jogo", sentenceA1: "Did you catch the game?", sentenceA2: "Did you catch the game last night? The final was incredible.", sentenceA1Pt: "Você assistiu o jogo?", sentenceA2Pt: "Assistiu o jogo ontem? O final foi incrível." },
    { english: "Overtime", portuguese: "Hora extra / Prorrogação", sentenceA1: "I worked overtime today.", sentenceA2: "I had to work overtime to finish the project.", sentenceA1Pt: "Fiz hora extra hoje.", sentenceA2Pt: "Tive que fazer hora extra para terminar o projeto." },
    { english: "For a living", portuguese: "Como profissão / Ganhar a vida", sentenceA1: "What do you do for a living?", sentenceA2: "She designs websites for a living and loves it.", sentenceA1Pt: "O que você faz da vida?", sentenceA2Pt: "Ela cria sites profissionalmente e adora." },
    { english: "Keep things exciting", portuguese: "Manter as coisas animadas", sentenceA1: "I like to keep things exciting.", sentenceA2: "We try new restaurants every weekend to keep things exciting.", sentenceA1Pt: "Gosto de manter as coisas animadas.", sentenceA2Pt: "Experimentamos restaurantes novos todo fim de semana." },
    { english: "Attitude", portuguese: "Atitude", sentenceA1: "She has a great attitude.", sentenceA2: "Having a positive attitude makes a big difference at work.", sentenceA1Pt: "Ela tem uma ótima atitude.", sentenceA2Pt: "Ter atitude positiva faz grande diferença no trabalho." },
    { english: "Conference", portuguese: "Conferência / Congresso", sentenceA1: "I went to a conference.", sentenceA2: "The technology conference had amazing speakers.", sentenceA1Pt: "Fui a uma conferência.", sentenceA2Pt: "A conferência de tecnologia teve palestrantes incríveis." },
    { english: "How", portuguese: "Como", sentenceA1: "How are you today?", sentenceA2: "How was your vacation? I heard you went to Europe.", sentenceA1Pt: "Como você está hoje?", sentenceA2Pt: "Como foram suas férias? Soube que foi para a Europa." },
    { english: "What", portuguese: "O que / Qual", sentenceA1: "What is your name?", sentenceA2: "What do you think about the new project?", sentenceA1Pt: "Qual é o seu nome?", sentenceA2Pt: "O que acha do novo projeto?" },
    { english: "Have a good one!", portuguese: "Tenha um bom dia / Tenha um bom!", sentenceA1: "Have a good one!", sentenceA2: "It was nice chatting. Have a good one!", sentenceA1Pt: "Tenha um bom dia!", sentenceA2Pt: "Foi bom conversar. Tenha um bom dia!" },
    { english: "Awesome", portuguese: "Incrível / Sensacional", sentenceA1: "That is awesome!", sentenceA2: "Your presentation was awesome! Everyone loved it.", sentenceA1Pt: "Isso é incrível!", sentenceA2Pt: "Sua apresentação foi incrível! Todos adoraram." },
    { english: "Make sense", portuguese: "Fazer sentido", sentenceA1: "Does that make sense?", sentenceA2: "I explained the directions twice. Does that make sense?", sentenceA1Pt: "Faz sentido?", sentenceA2Pt: "Expliquei as direções duas vezes. Faz sentido agora?" },
    { english: "How's it going?", portuguese: "Como vão as coisas?", sentenceA1: "Hey, how's it going?", sentenceA2: "How's it going? I haven't seen you since last week.", sentenceA1Pt: "E aí, como vai?", sentenceA2Pt: "Como vai? Não te vejo desde a semana passada." },
    { english: "What's up?", portuguese: "E aí? / O que está rolando?", sentenceA1: "What's up? All good?", sentenceA2: "What's up? I heard you started a new job.", sentenceA1Pt: "E aí, tudo bem?", sentenceA2Pt: "E aí? Soube que você começou um emprego novo." },
    // New ones:
    { english: "Weather", portuguese: "Clima / Tempo", sentenceA1: "The weather is hot.", sentenceA2: "I love cold weather because I can wear my favorite coats.", sentenceA1Pt: "O tempo está quente.", sentenceA2Pt: "Adoro clima frio porque posso usar meus casacos favoritos." },
    { english: "Busy", portuguese: "Ocupado(a)", sentenceA1: "I am very busy.", sentenceA2: "She has a very busy schedule today with meetings back-to-back.", sentenceA1Pt: "Estou muito ocupado.", sentenceA2Pt: "Ela está com uma agenda muito ocupada hoje com reuniões seguidas." },
    { english: "Colleague", portuguese: "Colega de trabalho", sentenceA1: "He is my colleague.", sentenceA2: "My colleague helped me finish the report on Friday.", sentenceA1Pt: "Ele é meu colega.", sentenceA2Pt: "Meu colega me ajudou a finalizar o relatório na sexta-feira." }
  ],
  slangs: [
    { english: "Lit / Fire", portuguese: "Massa / Muito legal / Demais", sentenceA1: "That party was lit!", sentenceA2: "The concert last night was absolutely lit.", sentenceA1Pt: "Aquela festa foi demais!", sentenceA2Pt: "O show ontem à noite foi absolutamente demais." },
    { english: "No cap", portuguese: "Sem mentira / Verdade", sentenceA1: "No cap, it was amazing.", sentenceA2: "No cap, that was the best pizza I ever tasted.", sentenceA1Pt: "Sem mentira, foi incrível.", sentenceA2Pt: "Sem mentira, foi a melhor pizza que já comi." },
    { english: "Hyped", portuguese: "Empolgado", sentenceA1: "I am so hyped!", sentenceA2: "Everyone is hyped about the new Marvel movie.", sentenceA1Pt: "Estou muito empolgado!", sentenceA2Pt: "Todo mundo está empolgado com o novo filme da Marvel." },
    { english: "Down (to do something)", portuguese: "Topar / Estar a fim", sentenceA1: "I am down to go.", sentenceA2: "Are you down to try the new sushi restaurant?", sentenceA1Pt: "Estou a fim de ir.", sentenceA2Pt: "Está a fim de experimentar o novo restaurante de sushi?" },
    { english: "Deets", portuguese: "Detalhes", sentenceA1: "Give me the deets.", sentenceA2: "Send me the deets about the party.", sentenceA1Pt: "Me dá os detalhes.", sentenceA2Pt: "Manda os detalhes sobre a festa." },
    { english: "Heads up", portuguese: "Aviso / Alerta", sentenceA1: "Heads up, it is raining.", sentenceA2: "Heads up, the boss is in a bad mood today.", sentenceA1Pt: "Só avisando, está chovendo.", sentenceA2Pt: "Só avisando, o chefe está de mau humor hoje." },
    { english: "Spaced out", portuguese: "Distraído(a) / No mundo da lua", sentenceA1: "Sorry, I spaced out.", sentenceA2: "I completely spaced out during the meeting.", sentenceA1Pt: "Desculpa, me distraí.", sentenceA2Pt: "Me distraí completamente durante a reunião." },
    { english: "Swamped", portuguese: "Atolado(a) de trabalho", sentenceA1: "I am swamped with work.", sentenceA2: "I cannot go out tonight, I am totally swamped.", sentenceA1Pt: "Estou atolado de trabalho.", sentenceA2Pt: "Não posso sair hoje, estou totalmente atolado." },
    { english: "Chill", portuguese: "Relaxar / Tranquilo", sentenceA1: "Let us chill at home.", sentenceA2: "We stayed home and chilled all weekend watching movies.", sentenceA1Pt: "Vamos relaxar em casa.", sentenceA2Pt: "Ficamos em casa e relaxamos o fim de semana assistindo filmes." },
    { english: "Ghost", portuguese: "Ignorar / Sumir", sentenceA1: "He ghosted me.", sentenceA2: "She ghosted me after our second date.", sentenceA1Pt: "Ele me deixou no vácuo.", sentenceA2Pt: "Ela me deixou no vácuo depois do segundo encontro." },
    { english: "Flex", portuguese: "Exibir-se / Ostentar", sentenceA1: "Stop flexing!", sentenceA2: "He always flexes his new sneakers on social media.", sentenceA1Pt: "Para de se exibir!", sentenceA2Pt: "Ele sempre se exibe com seus tênis novos nas redes sociais." },
    { english: "Salty", sentenceA1: "Why are you so salty?", sentenceA2: "She got salty because nobody liked her photo.", sentenceA1Pt: "Por que está tão irritado?", sentenceA2Pt: "Ela ficou irritada porque ninguém curtiu a foto dela.", portuguese: "Irritado(a) / Ressentido(a)" },
    { english: "Tea", portuguese: "Fofoca", sentenceA1: "Spill the tea!", sentenceA2: "I heard some tea about our neighbors.", sentenceA1Pt: "Conta a fofoca!", sentenceA2Pt: "Soube de uma fofoca sobre nossos vizinhos." },
    // New ones:
    { english: "Bet", portuguese: "Pode apostar / Com certeza", sentenceA1: "Are we going? Bet!", sentenceA2: "You think we can finish on time? Bet, let's start.", sentenceA1Pt: "Nós vamos? Com certeza!", sentenceA2Pt: "Você acha que podemos terminar no prazo? Com certeza, vamos começar." },
    { english: "Bummer", portuguese: "Que pena / Chateação", sentenceA1: "That is a bummer.", sentenceA2: "The concert was canceled. What a bummer!", sentenceA1Pt: "Que pena.", sentenceA2Pt: "O show foi cancelado. Que chateação!" },
    { english: "Slay", portuguese: "Arrasar", sentenceA1: "You slay in that outfit!", sentenceA2: "She did an amazing job on the presentation, she really slayed.", sentenceA1Pt: "Você arrasou com essa roupa!", sentenceA2Pt: "Ela fez um trabalho incrível na apresentação, ela realmente arrasou." },
    { english: "For real", portuguese: "Sério / De verdade", sentenceA1: "Are you for real?", sentenceA2: "I got a promotion, for real! I'm so excited.", sentenceA1Pt: "É sério?", sentenceA2Pt: "Fui promovido, de verdade! Estou muito animado." }
  ],
  shopping: [
    { english: "Fitting room", portuguese: "Provador", sentenceA1: "Where is the fitting room?", sentenceA2: "The fitting rooms are at the back of the store.", sentenceA1Pt: "Onde é o provador?", sentenceA2Pt: "Os provadores ficam no fundo da loja." },
    { english: "Size (Small, Medium, Large)", portuguese: "Tamanho (P, M, G)", sentenceA1: "I need a medium.", sentenceA2: "Do you have this in a size small? The medium is too loose.", sentenceA1Pt: "Preciso de um médio.", sentenceA2Pt: "Tem no tamanho P? O M está muito largo." },
    { english: "Tight / Loose", portuguese: "Apertado / Largo", sentenceA1: "This is too tight.", sentenceA2: "The pants are tight around the waist. Do you have a larger size?", sentenceA1Pt: "Está muito apertado.", sentenceA2Pt: "A calça está apertada na cintura. Tem tamanho maior?" },
    { english: "Receipt", portuguese: "Recibo / Nota fiscal", sentenceA1: "I need the receipt.", sentenceA2: "Keep your receipt in case you need to exchange the item.", sentenceA1Pt: "Preciso do recibo.", sentenceA2Pt: "Guarde o recibo caso precise trocar o item." },
    { english: "Tags", portuguese: "Etiquetas", sentenceA1: "Remove the tags, please.", sentenceA2: "Do not remove the tags if you are not sure you want to keep it.", sentenceA1Pt: "Retire as etiquetas, por favor.", sentenceA2Pt: "Não remova as etiquetas se não tem certeza que quer ficar com o item." },
    { english: "Trying on", portuguese: "Experimentando", sentenceA1: "I am trying this on.", sentenceA2: "Can I try on these jeans? I am not sure about the size.", sentenceA1Pt: "Estou experimentando isto.", sentenceA2Pt: "Posso experimentar estas calças? Não tenho certeza do tamanho." },
    { english: "Hanger", portuguese: "Cabide", sentenceA1: "Put it on the hanger.", sentenceA2: "Please put the clothes back on the hanger after trying them.", sentenceA1Pt: "Coloque no cabide.", sentenceA2Pt: "Coloque as roupas de volta no cabide depois de experimentar." },
    { english: "Sold out", portuguese: "Esgotado", sentenceA1: "This size is sold out.", sentenceA2: "The sneakers I wanted are sold out in my size.", sentenceA1Pt: "Este tamanho esgotou.", sentenceA2Pt: "Os tênis que eu queria esgotaram no meu tamanho." },
    { english: "Mannequin", portuguese: "Manequim", sentenceA1: "I want that outfit.", sentenceA2: "The outfit on the mannequin in the window looks really stylish.", sentenceA1Pt: "Quero aquela roupa.", sentenceA2Pt: "A roupa no manequim da vitrine está muito estilosa." },
    { english: "Out of stock", portuguese: "Fora de estoque", sentenceA1: "It is out of stock.", sentenceA2: "The jacket is out of stock but they can order it for you.", sentenceA1Pt: "Está fora de estoque.", sentenceA2Pt: "A jaqueta está fora de estoque mas podem encomendar." },
    { english: "T-shirt / Shirt", portuguese: "Camiseta / Camisa", sentenceA1: "I like this t-shirt.", sentenceA2: "I bought a white t-shirt and a blue shirt for the trip.", sentenceA1Pt: "Gosto desta camiseta.", sentenceA2Pt: "Comprei uma camiseta branca e uma camisa azul para a viagem." },
    { english: "Pants / Jeans", portuguese: "Calças / Jeans", sentenceA1: "I need new pants.", sentenceA2: "These jeans fit perfectly. I do not need another pair.", sentenceA1Pt: "Preciso de calças novas.", sentenceA2Pt: "Estas calças servem perfeitamente. Não preciso de outro par." },
    { english: "Dress", portuguese: "Vestido", sentenceA1: "This dress is beautiful.", sentenceA2: "She wore a red dress to the party and everyone complimented her.", sentenceA1Pt: "Este vestido é lindo.", sentenceA2Pt: "Ela usou um vestido vermelho e todos a elogiaram." },
    { english: "Skirt", portuguese: "Saia", sentenceA1: "I want to buy a skirt.", sentenceA2: "This plaid skirt goes well with a black blouse and boots.", sentenceA1Pt: "Quero comprar uma saia.", sentenceA2Pt: "Esta saia xadrez combina com blusa preta e botas." },
    { english: "Jacket", portuguese: "Jaqueta", sentenceA1: "I need a jacket.", sentenceA2: "This leather jacket is on sale for half price.", sentenceA1Pt: "Preciso de uma jaqueta.", sentenceA2Pt: "Esta jaqueta de couro está na promoção pela metade do preço." },
    { english: "Coat", portuguese: "Casaco", sentenceA1: "This coat is warm.", sentenceA2: "Bring a heavy coat because the temperature will drop tonight.", sentenceA1Pt: "Este casaco é quente.", sentenceA2Pt: "Leve um casaco pesado porque a temperatura vai cair hoje à noite." },
    { english: "Sneakers", portuguese: "Tênis", sentenceA1: "I love these sneakers.", sentenceA2: "I saved money for two months to buy these limited edition sneakers.", sentenceA1Pt: "Amo estes tênis.", sentenceA2Pt: "Economizei por dois meses para comprar estes tênis de edição limitada." },
    { english: "High heels", portuguese: "Salto alto", sentenceA1: "These heels are pretty.", sentenceA2: "I can only wear high heels for a few hours before my feet hurt.", sentenceA1Pt: "Estes saltos são bonitos.", sentenceA2Pt: "Só consigo usar salto alto por algumas horas antes dos pés doerem." },
    // New ones:
    { english: "To exchange", portuguese: "Trocar", sentenceA1: "Can I exchange this?", sentenceA2: "I need to exchange this shirt for a smaller size.", sentenceA1Pt: "Posso trocar isso?", sentenceA2Pt: "Preciso trocar esta camisa por um tamanho menor." },
    { english: "Clearance / Sale", portuguese: "Liquidação / Saldo", sentenceA1: "Is this on clearance?", sentenceA2: "The winter coats are on clearance now since spring is starting.", sentenceA1Pt: "Isto está na liquidação?", sentenceA2Pt: "Os casacos de inverno estão na liquidação agora que a primavera está começando." },
    { english: "Store credit", portuguese: "Crédito na loja", sentenceA1: "Can I get store credit?", sentenceA2: "Since I didn't have the receipt, they gave me store credit instead of a refund.", sentenceA1Pt: "Posso receber crédito na loja?", sentenceA2Pt: "Como eu não tinha o recibo, eles me deram crédito na loja em vez de um reembolso." }
  ],
  beauty: [
    { english: "Foundation", portuguese: "Base de maquiagem", sentenceA1: "I need foundation.", sentenceA2: "I use a light foundation that matches my skin tone.", sentenceA1Pt: "Preciso de base.", sentenceA2Pt: "Uso uma base leve que combina com meu tom de pele." },
    { english: "Concealer", portuguese: "Corretivo", sentenceA1: "I use concealer.", sentenceA2: "This concealer covers dark circles very well.", sentenceA1Pt: "Uso corretivo.", sentenceA2Pt: "Este corretivo cobre olheiras muito bem." },
    { english: "Moisturizer", portuguese: "Hidratante", sentenceA1: "I need a moisturizer.", sentenceA2: "I apply moisturizer every morning after washing my face.", sentenceA1Pt: "Preciso de hidratante.", sentenceA2Pt: "Aplico hidratante toda manhã depois de lavar o rosto." },
    { english: "Cleanser", portuguese: "Gel de limpeza / Sabonete facial", sentenceA1: "I use a gentle cleanser.", sentenceA2: "A good cleanser removes all makeup without drying your skin.", sentenceA1Pt: "Uso um limpador suave.", sentenceA2Pt: "Um bom limpador remove toda a maquiagem sem ressecar a pele." },
    { english: "Heat protectant", portuguese: "Protetor térmico", sentenceA1: "Use heat protectant first.", sentenceA2: "Always spray heat protectant before using a flat iron.", sentenceA1Pt: "Use protetor térmico primeiro.", sentenceA2Pt: "Sempre borrife protetor térmico antes de usar a chapinha." },
    { english: "Leave-in conditioner", portuguese: "Condicionador leave-in", sentenceA1: "I use leave-in conditioner.", sentenceA2: "Leave-in conditioner keeps my curly hair soft all day.", sentenceA1Pt: "Uso condicionador sem enxágue.", sentenceA2Pt: "O condicionador sem enxágue mantém meu cabelo macio o dia todo." },
    { english: "Cruelty-free", portuguese: "Livre de crueldade / Não testado em animais", sentenceA1: "This is cruelty-free.", sentenceA2: "I only buy cruelty-free brands because I care about animals.", sentenceA1Pt: "Não testa em animais.", sentenceA2Pt: "Só compro marcas cruelty-free porque me preocupo com animais." },
    { english: "Skincare routine", portuguese: "Rotina de cuidados com a pele", sentenceA1: "I have a skincare routine.", sentenceA2: "My skincare routine includes cleanser, toner, serum, and moisturizer.", sentenceA1Pt: "Tenho uma rotina de skincare.", sentenceA2Pt: "Minha rotina inclui limpador, tônico, sérum e hidratante." },
    // New ones:
    { english: "Sunscreen", portuguese: "Protetor solar", sentenceA1: "Apply sunscreen daily.", sentenceA2: "You should apply sunscreen every day, even when it is cloudy.", sentenceA1Pt: "Aplique protetor solar diariamente.", sentenceA2Pt: "Você deveria aplicar protetor solar todos os dias, mesmo quando está nublado." },
    { english: "Primer", portuguese: "Primer", sentenceA1: "Apply primer first.", sentenceA2: "A makeup primer helps your foundation stay on longer throughout the day.", sentenceA1Pt: "Aplique o primer primeiro.", sentenceA2Pt: "O primer facial ajuda a base a durar mais tempo durante o dia." },
    { english: "Micellar water", portuguese: "Água micelar", sentenceA1: "Clean with micellar water.", sentenceA2: "I use micellar water on a cotton pad to remove makeup before washing my face.", sentenceA1Pt: "Limpe com água micelar.", sentenceA2Pt: "Uso água micelar em um algodão para remover a maquiagem antes de lavar o rosto." },
    { english: "Shampoo / Conditioner", portuguese: "Shampoo / Condicionador", sentenceA1: "I need shampoo.", sentenceA2: "This moisturizing shampoo and conditioner set is great for dry hair.", sentenceA1Pt: "Preciso de shampoo.", sentenceA2Pt: "Este conjunto de shampoo e condicionador hidratantes é ótimo para cabelos secos." },
    { english: "Lip balm", portuguese: "Protetor labial", sentenceA1: "My lips are dry. I need lip balm.", sentenceA2: "This organic lip balm prevents dry lips during the winter months.", sentenceA1Pt: "Meus lábios estão secos. Preciso de protetor labial.", sentenceA2Pt: "Este protetor labial orgânico previne lábios secos durante os meses de inverno." }
  ],
  carrental: [
    { english: "Insurance", portuguese: "Seguro", sentenceA1: "I want insurance.", sentenceA2: "The insurance covers any damage during the rental period.", sentenceA1Pt: "Quero seguro.", sentenceA2Pt: "O seguro cobre qualquer dano durante o período de aluguel." },
    { english: "Toll pass", portuguese: "Passe de pedágio", sentenceA1: "Do I need a toll pass?", sentenceA2: "The toll pass is convenient because you do not need to stop.", sentenceA1Pt: "Preciso de passe de pedágio?", sentenceA2Pt: "O passe de pedágio é prático porque não precisa parar." },
    { english: "Deposit", portuguese: "Depósito / Caução", sentenceA1: "How much is the deposit?", sentenceA2: "They charged a five hundred dollar deposit on my credit card.", sentenceA1Pt: "Quanto é o depósito?", sentenceA2Pt: "Cobraram um depósito de quinhentos dólares no meu cartão." },
    { english: "Full tank", portuguese: "Tanque cheio", sentenceA1: "The tank is full.", sentenceA2: "Please return the car with a full tank or you will be charged.", sentenceA1Pt: "O tanque está cheio.", sentenceA2Pt: "Devolva o carro com o tanque cheio senão será cobrado a mais." },
    { english: "Additional driver", portuguese: "Motorista adicional", sentenceA1: "I want to add a driver.", sentenceA2: "Adding an additional driver costs twenty dollars per day.", sentenceA1Pt: "Quero adicionar um motorista.", sentenceA2Pt: "Adicionar um motorista extra custa vinte dólares por dia." },
    { english: "Automatic transmission", portuguese: "Câmbio automático", sentenceA1: "I want automatic.", sentenceA2: "I prefer automatic transmission because I am not used to manual.", sentenceA1Pt: "Quero automático.", sentenceA2Pt: "Prefiro automático porque não estou acostumado com manual." },
    { english: "Trunk", portuguese: "Porta-malas", sentenceA1: "Open the trunk, please.", sentenceA2: "The trunk is large enough for three suitcases.", sentenceA1Pt: "Abra o porta-malas.", sentenceA2Pt: "O porta-malas é grande o suficiente para três malas." },
    { english: "Prepaid fuel", portuguese: "Combustível pré-pago", sentenceA1: "I chose prepaid fuel.", sentenceA2: "With prepaid fuel you do not need to refill before returning.", sentenceA1Pt: "Escolhi combustível pré-pago.", sentenceA2Pt: "Com combustível pré-pago não precisa reabastecer antes de devolver." },
    { english: "Flat tire", portuguese: "Pneu furado", sentenceA1: "I have a flat tire.", sentenceA2: "We got a flat tire on the highway and had to call for help.", sentenceA1Pt: "Estou com pneu furado.", sentenceA2Pt: "Tivemos um pneu furado na rodovia e ligamos para assistência." },
    { english: "Roadside assistance", portuguese: "Assistência na estrada", sentenceA1: "Call roadside assistance.", sentenceA2: "The rental includes free roadside assistance twenty-four hours.", sentenceA1Pt: "Ligue para a assistência.", sentenceA2Pt: "O aluguel inclui assistência na estrada gratuita 24 horas." },
    { english: "Scratched", portuguese: "Arranhado", sentenceA1: "The car is scratched.", sentenceA2: "Make sure to report any scratches before you leave.", sentenceA1Pt: "O carro está arranhado.", sentenceA2Pt: "Relate quaisquer arranhões antes de sair da locadora." },
    { english: "Dented", portuguese: "Amassado", sentenceA1: "The door is dented.", sentenceA2: "The car was already dented when I picked it up.", sentenceA1Pt: "A porta está amassada.", sentenceA2Pt: "O carro já estava amassado quando peguei." },
    { english: "Collision Damage Waiver (CDW)", portuguese: "Isenção de responsabilidade por danos por colisão", sentenceA1: "I want the CDW.", sentenceA2: "The CDW covers the full cost of repairs in case of an accident.", sentenceA1Pt: "Quero o seguro contra colisão.", sentenceA2Pt: "O CDW cobre o custo total de reparos em caso de acidente." },
    { english: "Liability Insurance", portuguese: "Seguro contra terceiros", sentenceA1: "I need liability insurance.", sentenceA2: "Liability insurance protects you if you damage another vehicle.", sentenceA1Pt: "Preciso de seguro contra terceiros.", sentenceA2Pt: "Liability insurance protege se causar dano a outro veículo." },
    // New ones:
    { english: "GPS navigation", portuguese: "Navegador GPS", sentenceA1: "Does the car have GPS?", sentenceA2: "I paid an extra ten dollars for a GPS navigation system.", sentenceA1Pt: "O carro tem GPS?", sentenceA2Pt: "Paguei dez dólares extras por um sistema de navegação GPS." },
    { english: "Rental agreement", portuguese: "Contrato de aluguel", sentenceA1: "Sign the agreement.", sentenceA2: "Please read the rental agreement carefully before signing.", sentenceA1Pt: "Assine o contrato.", sentenceA2Pt: "Por favor, leia o contrato de aluguel atentamente antes de assinar." },
    { english: "SUV", portuguese: "Carro utilitário esportivo / SUV", sentenceA1: "I rented an SUV.", sentenceA2: "We upgraded to an SUV because we needed more space for our ski gear.", sentenceA1Pt: "Aluguei um SUV.", sentenceA2Pt: "Nós fizemos um upgrade para um SUV porque precisávamos de mais espaço para nossos equipamentos de esqui." },
    { english: "Unlimited mileage", portuguese: "Quilometragem ilimitada", sentenceA1: "Does it have unlimited mileage?", sentenceA2: "Our rental has unlimited mileage, so we can drive as far as we want.", sentenceA1Pt: "Tem quilometragem ilimitada?", sentenceA2Pt: "Nosso aluguel tem quilometragem ilimitada, então podemos dirigir o quanto quisermos." }
  ],
  supermarket: [
    { english: "Grocery store / Supermarket", portuguese: "Supermercado / Mercearia", sentenceA1: "I go to the supermarket.", sentenceA2: "The grocery store near my house has great organic products.", sentenceA1Pt: "Vou ao supermercado.", sentenceA2Pt: "O supermercado perto de casa tem ótimos produtos orgânicos." },
    { english: "Produce section", portuguese: "Hortifrúti / FLV", sentenceA1: "Fruits are in produce.", sentenceA2: "I always start shopping in the produce section.", sentenceA1Pt: "Frutas ficam no hortifrúti.", sentenceA2Pt: "Sempre começo as compras na seção de hortifrúti." },
    { english: "Bakery", portuguese: "Padaria", sentenceA1: "The bakery smells great.", sentenceA2: "The bakery makes fresh bread every morning.", sentenceA1Pt: "A padaria cheira bem.", sentenceA2Pt: "A padaria faz pão fresco toda manhã." },
    { english: "Deli counter", portuguese: "Fiambreria / Frios", sentenceA1: "I want cheese from the deli.", sentenceA2: "The deli counter has a wide variety of imported cheeses.", sentenceA1Pt: "Quero queijo do balcão de frios.", sentenceA2Pt: "O balcão de frios tem grande variedade de queijos importados." },
    { english: "Dairy section", portuguese: "Laticínios", sentenceA1: "Milk is in dairy.", sentenceA2: "I need to pick up yogurt and butter from the dairy section.", sentenceA1Pt: "Leite fica nos laticínios.", sentenceA2Pt: "Preciso pegar iogurte e manteiga nos laticínios." },
    { english: "Frozen foods aisle", portuguese: "Corredor de congelados", sentenceA1: "Ice cream is in frozen.", sentenceA2: "The frozen foods aisle has pre-made meals for busy nights.", sentenceA1Pt: "Sorvete fica nos congelados.", sentenceA2Pt: "O corredor de congelados tem refeições prontas para noites corridas." },
    { english: "Meat department / Butcher", portuguese: "Açougue / Carnes", sentenceA1: "I need meat from the butcher.", sentenceA2: "The butcher can cut the meat any way you prefer.", sentenceA1Pt: "Preciso de carne do açougueiro.", sentenceA2Pt: "O açougueiro pode cortar a carne do jeito que preferir." },
    { english: "Grocery cart / Shopping cart", portuguese: "Carrinho de compras", sentenceA1: "I need a cart.", sentenceA2: "The shopping carts are at the entrance of the supermarket.", sentenceA1Pt: "Preciso de um carrinho.", sentenceA2Pt: "Os carrinhos ficam na entrada do supermercado." },
    { english: "Shopping basket", portuguese: "Cesta de compras", sentenceA1: "I only need a basket.", sentenceA2: "I grabbed a basket because I only needed a few items.", sentenceA1Pt: "Só preciso de uma cesta.", sentenceA2Pt: "Peguei uma cesta porque só precisava de alguns itens." },
    { english: "Grocery aisle", portuguese: "Corredor do supermercado", sentenceA1: "It is in aisle three.", sentenceA2: "The pasta and sauces are in aisle number seven.", sentenceA1Pt: "Está no corredor três.", sentenceA2Pt: "As massas e molhos estão no corredor número sete." },
    { english: "Checkout lane / Register", portuguese: "Fila do caixa / Caixa", sentenceA1: "Go to the checkout.", sentenceA2: "The express checkout lane is for ten items or fewer.", sentenceA1Pt: "Vá ao caixa.", sentenceA2Pt: "O caixa rápido é para dez itens ou menos." },
    { english: "Cashier", portuguese: "Operador(a) de caixa", sentenceA1: "The cashier is fast.", sentenceA2: "The cashier asked if I wanted to pay in cash or by card.", sentenceA1Pt: "O caixa é rápido.", sentenceA2Pt: "O caixa perguntou se eu queria pagar em dinheiro ou cartão." },
    { english: "Self-checkout", portuguese: "Autoatendimento", sentenceA1: "I prefer self-checkout.", sentenceA2: "Self-checkout machines are quicker when you have few items.", sentenceA1Pt: "Prefiro o autoatendimento.", sentenceA2Pt: "As máquinas de autoatendimento são mais rápidas com poucos itens." },
    { english: "Receipt", portuguese: "Cupom fiscal", sentenceA1: "I want the receipt.", sentenceA2: "Always check your receipt to make sure you were charged correctly.", sentenceA1Pt: "Quero o recibo.", sentenceA2Pt: "Sempre confira o recibo para ver se foi cobrado corretamente." },
    { english: "Paper bag / Plastic bag", portuguese: "Sacola de papel / plástica", sentenceA1: "Paper bag, please.", sentenceA2: "Many stores charge for plastic bags to encourage reusable ones.", sentenceA1Pt: "Sacola de papel, por favor.", sentenceA2Pt: "Muitas lojas cobram pelas sacolas plásticas para incentivar reutilizáveis." },
    { english: "Organic", portuguese: "Orgânico", sentenceA1: "I buy organic food.", sentenceA2: "Organic vegetables are more expensive but taste much better.", sentenceA1Pt: "Compro comida orgânica.", sentenceA2Pt: "Legumes orgânicos são mais caros mas o sabor é muito melhor." },
    { english: "Loyalty card", portuguese: "Cartão fidelidade", sentenceA1: "I have a loyalty card.", sentenceA2: "Use your loyalty card at checkout to earn points.", sentenceA1Pt: "Tenho cartão fidelidade.", sentenceA2Pt: "Use seu cartão fidelidade no caixa para acumular pontos." },
    // New ones:
    { english: "Canned goods", portuguese: "Alimentos enlatados / Enlatados", sentenceA1: "I need canned tomatoes.", sentenceA2: "The canned goods like beans and soups are stored in aisle five.", sentenceA1Pt: "Preciso de tomates enlatados.", sentenceA2Pt: "Os alimentos enlatados como feijões e sopas ficam no corredor cinco." },
    { english: "Spices", portuguese: "Especiarias / Temperos", sentenceA1: "Where are the spices?", sentenceA2: "I bought fresh pepper and oregano in the spices section.", sentenceA1Pt: "Onde ficam os temperos?", sentenceA2Pt: "Comprei pimenta fresca e orégano na seção de temperos." },
    { english: "Barcode", portuguese: "Código de barras", sentenceA1: "Scan the barcode.", sentenceA2: "The scanner could not read the barcode on this cereal box.", sentenceA1Pt: "Escaneie o código de barras.", sentenceA2Pt: "O scanner não conseguiu ler o código de barras nesta caixa de cereal." },
    { english: "Expiration date", portuguese: "Data de validade", sentenceA1: "Check the expiration date.", sentenceA2: "You should always check the expiration date on dairy products before buying.", sentenceA1Pt: "Confira a validade.", sentenceA2Pt: "Você sempre deveria verificar a data de validade em laticínios antes de comprar." }
  ]
};

// Read original file
let content = fs.readFileSync('data/scenarios.ts', 'utf8');

// For each scenario, locate vocabulary: [ ... ] and swap it
for (const id of ids) {
  const vocab = newVocabularies[id];
  if (!vocab) continue;
  
  const idMarker = "id: '" + id + "'";
  const idIdx = content.indexOf(idMarker);
  if (idIdx === -1) {
    console.log("SKIP: Scenario " + id + " not found!");
    continue;
  }
  
  const vocabMarker = "vocabulary: [";
  const vocabStart = content.indexOf(vocabMarker, idIdx);
  if (vocabStart === -1) {
    console.log("SKIP: Vocabulary array not found for " + id);
    continue;
  }
  
  // Find matching closing bracket
  const bracket = vocabStart + vocabMarker.length - 1;
  let depth = 1;
  let i = bracket + 1;
  while (depth > 0 && i < content.length) {
    if (content[i] === '[') depth++;
    if (content[i] === ']') depth--;
    i++;
  }
  const vocabEnd = i; // covers the closing ']'
  
  // Construct the new array string block
  let newVocabStr = "vocabulary: [\n";
  for (const item of vocab) {
    newVocabStr += `      { english: ${JSON.stringify(item.english)}, portuguese: ${JSON.stringify(item.portuguese)},\n        sentenceA1: ${JSON.stringify(item.sentenceA1)},\n        sentenceA2: ${JSON.stringify(item.sentenceA2)},\n        sentenceA1Pt: ${JSON.stringify(item.sentenceA1Pt)},\n        sentenceA2Pt: ${JSON.stringify(item.sentenceA2Pt)}\n      },\n`;
  }
  newVocabStr += "    ]";
  
  // Swap block
  content = content.substring(0, vocabStart) + newVocabStr + content.substring(vocabEnd);
  console.log("Updated vocabulary for: " + id + " (total " + vocab.length + " items)");
}

fs.writeFileSync('data/scenarios.ts', content, 'utf8');
console.log("Finished rebuilding all vocabularies!");
