const fs = require('fs');
let content = fs.readFileSync('data/scenarios.ts', 'utf8');

const escapeRegex = (string) => {
  return string.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');
};

const replacements = [
  // Cafe
  {
    qA1: "What does Emily order to drink?",
    repA1: "questionsA1: [\n        { question: 'What is the main topic of the text?', questionPt: 'Qual é o tópico principal do texto?', options: ['Emily\\'s morning routine at the coffee shop', 'Emily cooking breakfast at home', 'Emily working as a barista', 'Emily buying a book'], correctIndex: 0 },\n        { question: 'What does \"it is her turn\" mean?', questionPt: 'O que significa \"it is her turn\"?', options: ['She is spinning around', 'She is leaving the shop', 'She is the next person in line to order', 'She is sleeping'], correctIndex: 2 },\n        { question: 'Why does the cashier ask for her name?', questionPt: 'Por que o caixa pergunta o nome dela?', options: ['To be her friend', 'To write it on the cup so they know it\\'s her order', 'To call the police', 'Because it is a test'], correctIndex: 1 },\n        { question: 'What can we infer about Emily\\'s feelings?', questionPt: 'O que podemos inferir sobre os sentimentos de Emily?', options: ['She is enjoying a peaceful morning', 'She is angry about the price', 'She is in a rush and stressed', 'She hates coffee'], correctIndex: 0 },\n      ]",
    qA2: "What specific modifications did Emily make to her drink?",
    repA2: "questionsA2: [\n        { question: 'What is the central focus of this narrative?', questionPt: 'Qual é o foco central desta narrativa?', options: ['Emily\\'s daily morning ritual of enjoying artisanal coffee before work', 'The process of making caramel macchiatos', 'The history of Elm Street', 'Emily\\'s complaints about the café'], correctIndex: 0 },\n        { question: 'What is a synonym for \"commuters\" as used in the text?', questionPt: 'Qual é um sinônimo para \"commuters\" como usado no texto?', options: ['Baristas', 'People traveling regularly to work', 'Tourists', 'Children'], correctIndex: 1 },\n        { question: 'Why did the cashier ask for a name for the cup?', questionPt: 'Por que o caixa pediu um nome para o copo?', options: ['Because he was making a joke', 'To identify her customized drink in a fast-paced environment', 'Because he hates Emily', 'Because it is her real name'], correctIndex: 1 },\n        { question: 'What does \"energized\" imply at the end of the text?', questionPt: 'O que \"energized\" implica no final do texto?', options: ['She was extremely tired', 'She felt sad and down', 'She felt active and full of energy to start her day', 'She didn\\'t like the taste'], correctIndex: 2 },\n      ]"
  },
  // Tech
  {
    qA1: "How much does the SIM card cost?",
    repA1: "questionsA1: [\n        { question: 'What is the main topic of the text?', questionPt: 'Qual é o tópico principal do texto?', options: ['Ana setting up her phone to use in the US', 'Ana buying a new smartphone', 'Ana fixing a broken TV', 'Ana taking photos in the park'], correctIndex: 0 },\n        { question: 'What does \"slow\" mean in the text?', questionPt: 'O que significa \"slow\" no texto?', options: ['It is working very well and fast', 'It is brand new', 'It takes a long time to load things', 'It is very cheap'], correctIndex: 2 },\n        { question: 'Why does Ana need a power adapter?', questionPt: 'Por que Ana precisa de um adaptador de tomada?', options: ['Because the plugs in the US are different from her country', 'Because she likes the color black', 'Because it is cheaper', 'Because her phone is broken'], correctIndex: 0 },\n        { question: 'What can we infer about the map app?', questionPt: 'O que podemos inferir sobre o aplicativo de mapa?', options: ['It uses a lot of internet data', 'It is very useful because she can use it offline', 'It is a game', 'It doesn\\'t work'], correctIndex: 1 },\n      ]",
    qA2: "Why did Ana choose the premium plan?",
    repA2: "questionsA2: [\n        { question: 'What is the primary theme of this story?', questionPt: 'Qual é o tema principal desta história?', options: ['The challenge and process of staying connected digitally while traveling abroad', 'The dangers of dropping a phone', 'How to install a screen protector', 'Transferring data manually'], correctIndex: 0 },\n        { question: 'What is the best synonym for \"opted\"?', questionPt: 'Qual é o melhor sinônimo para \"opted\"?', options: ['Rejected', 'Chose or selected', 'Ignored', 'Complained'], correctIndex: 1 },\n        { question: 'Why did Ana choose the premium plan?', questionPt: 'Por que Ana escolheu o plano premium?', options: ['Because she wanted to share her Wi-Fi and use GPS constantly', 'To provide good customer service', 'Because her phone was completely dead', 'Because it was a requirement'], correctIndex: 0 },\n        { question: 'What does \"precious resources\" refer to in the text?', questionPt: 'A que se refere \"precious resources\" no texto?', options: ['Money and gold', 'Coffee and tea', 'Wi-Fi passwords and power outlets', 'Friends and family'], correctIndex: 2 },\n      ]"
  },
  // Smalltalk
  {
    qA1: "Where does Mark meet his neighbor?",
    repA1: "questionsA1: [\n        { question: 'What is the main idea of this text?', questionPt: 'Qual é a ideia principal deste texto?', options: ['Mark has a friendly morning chat with his neighbor', 'Mark hates his neighbor', 'Mark is stuck in the elevator', 'Mark goes to a bank'], correctIndex: 0 },\n        { question: 'What does \"friendly\" mean in the text?', questionPt: 'O que significa \"friendly\" no texto?', options: ['Mean and angry', 'Kind and pleasant', 'Cold and silent', 'Fast and loud'], correctIndex: 1 },\n        { question: 'Why do they talk about the weather?', questionPt: 'Por que eles falam sobre o tempo?', options: ['Because they are meteorologists', 'It is a common and polite topic for a quick chat', 'Because it is raining inside', 'To argue'], correctIndex: 1 },\n        { question: 'What can we infer about their relationship?', questionPt: 'O que podemos inferir sobre o relacionamento deles?', options: ['They are polite and have a good relationship', 'They are best friends', 'They never talk', 'They are angry at each other'], correctIndex: 0 },\n      ]",
    qA2: "What is the expected response to ",
    repA2: "questionsA2: [\n        { question: 'What is the general topic of this passage?', questionPt: 'Qual é o tópico geral desta passagem?', options: ['The history of Brooklyn', 'The cultural nuances of American small talk', 'How to order coffee', 'Applying for a job'], correctIndex: 1 },\n        { question: 'What does \"social lubricant\" imply?', questionPt: 'O que \"social lubricant\" implica?', options: ['Something that makes social interactions smoother and easier', 'A type of oil for machines', 'A way to avoid people', 'Something that causes arguments'], correctIndex: 0 },\n        { question: 'Why was Mark initially confused by \"How are you?\"', questionPt: 'Por que Mark ficou inicialmente confuso com \"How are you?\"?', options: ['He didn\\'t speak English at all', 'He didn\\'t know if it was a genuine question or just a greeting', 'He thought it was an insult', 'He didn\\'t hear the barista'], correctIndex: 1 },\n        { question: 'What can we infer about talking to strangers in the US?', questionPt: 'O que podemos inferir sobre conversar com estranhos nos EUA?', options: ['It is illegal', 'It can lead to genuine friendships if the topic is right', 'It always causes problems', 'People only talk about politics'], correctIndex: 1 },\n      ]"
  },
  // Slangs
  {
    qA1: "What does ",
    repA1: "questionsA1: [\n        { question: 'What is the main message of the text?', questionPt: 'Qual é a mensagem principal do texto?', options: ['Lucas is learning informal American expressions', 'Lucas is eating at a good restaurant', 'Lucas is angry at his friend', 'Lucas is buying a notebook'], correctIndex: 0 },\n        { question: 'What does \"hang out\" mean?', questionPt: 'O que significa \"hang out\"?', options: ['To hang clothes on a line', 'To spend time relaxing with friends', 'To go to sleep', 'To run away'], correctIndex: 1 },\n        { question: 'Why does Lucas write the new words in his notebook?', questionPt: 'Por que Lucas escreve as novas palavras em seu caderno?', options: ['Because he wants to forget them', 'Because his friend forces him to', 'To help him remember them later', 'To sell the notebook'], correctIndex: 2 },\n        { question: 'What can we infer about Lucas\\'s attitude?', questionPt: 'O que podemos inferir sobre a atitude de Lucas?', options: ['He is curious and wants to learn', 'He hates English', 'He thinks everything is boring', 'He is very sad'], correctIndex: 0 },\n      ]",
    qA2: "What does ",
    repA2: "questionsA2: [\n        { question: 'What is the primary theme of the story?', questionPt: 'Qual é o tema principal da história?', options: ['The difficulty of understanding American slang and idioms', 'The process of renting an apartment', 'A fight between roommates', 'Going to sleep early'], correctIndex: 0 },\n        { question: 'What is a good synonym for \"insane\" in the context of the story?', questionPt: 'Qual é um bom sinônimo para \"insane\" no contexto da história?', options: ['Mentally ill', 'Boring', 'Intense or crazy (in a positive way)', 'Quiet'], correctIndex: 2 },\n        { question: 'Why was Lucas confused when Jake said \"I\\'m down\"?', questionPt: 'Por que Lucas ficou confuso quando Jake disse \"I\\'m down\"?', options: ['Because Lucas thought Jake was sad', 'Because Jake was pointing at the floor', 'Because they were on the roof', 'Because Lucas didn\\'t hear him'], correctIndex: 0 },\n        { question: 'What is the implication of calling slang a \"secret weapon\"?', questionPt: 'Qual é a implicação de chamar as gírias de \"secret weapon\" (arma secreta)?', options: ['It is a dangerous tool', 'It is a highly effective skill for connecting with native speakers', 'It is illegal to use', 'It is a physical weapon'], correctIndex: 1 },\n      ]"
  },
  // Shopping
  {
    qA1: "What does Lisa want to buy?",
    repA1: "questionsA1: [\n        { question: 'What is the main event in the story?', questionPt: 'Qual é o evento principal da história?', options: ['Lisa buys a pretty red dress at the mall', 'Lisa works at a clothes store', 'Lisa buys food', 'Lisa buys a mirror'], correctIndex: 0 },\n        { question: 'What does \"try it on\" mean?', questionPt: 'O que significa \"try it on\"?', options: ['To wash the dress', 'To put the dress on to see if it fits', 'To tear the dress', 'To return the dress'], correctIndex: 1 },\n        { question: 'Why does Lisa smile when she looks in the mirror?', questionPt: 'Por que Lisa sorri quando se olha no espelho?', options: ['Because the mirror is funny', 'Because she likes how the dress looks on her', 'Because she sees a friend', 'Because the dress is too big'], correctIndex: 1 },\n        { question: 'What can we infer about the price?', questionPt: 'O que podemos inferir sobre o preço?', options: ['She couldn\\'t afford it', 'She paid for it in cash', 'It was free', 'She paid with a credit card'], correctIndex: 1 },\n      ]",
    qA2: "When did Lisa go to the mall?",
    repA2: "questionsA2: [\n        { question: 'What is the general idea of this text?', questionPt: 'Qual é a ideia geral deste texto?', options: ['How to design a dress', 'Lisa\\'s successful shopping trip to update her summer wardrobe', 'Returning a defective item', 'A very empty mall'], correctIndex: 1 },\n        { question: 'What does \"bustling\" mean?', questionPt: 'O que significa \"bustling\"?', options: ['Empty and quiet', 'Full of busy activity and people', 'Dark and scary', 'Cold and wet'], correctIndex: 1 },\n        { question: 'Why did the assistant say \"You\\'re in luck\"?', questionPt: 'Por que a assistente disse \"You\\'re in luck\"?', options: ['Because Lisa won the lottery', 'Because it was the very last dress in Lisa\\'s size', 'Because it was raining outside', 'Because the store was closing'], correctIndex: 1 },\n        { question: 'What does the idiom \"fit like a glove\" imply?', questionPt: 'O que a expressão idiomática \"fit like a glove\" implica?', options: ['It was too tight', 'It fit perfectly and comfortably', 'It looked like a hand', 'It was the wrong size'], correctIndex: 1 },\n      ]"
  },
  // Beauty
  {
    qA1: "Where does Julia go?",
    repA1: "questionsA1: [\n        { question: 'What is the main topic of the text?', questionPt: 'Qual é o tópico principal do texto?', options: ['Julia getting a new haircut and color at the salon', 'Julia buying a new dress', 'Julia washing her hair at home', 'Julia going to a party'], correctIndex: 0 },\n        { question: 'What does \"new look\" mean in the text?', questionPt: 'O que significa \"new look\" no texto?', options: ['A new pair of glasses', 'A change in her appearance', 'A new book', 'A new job'], correctIndex: 1 },\n        { question: 'Why does she wait for 30 minutes?', questionPt: 'Por que ela espera por 30 minutos?', options: ['For the blonde color to set in her hair', 'Because the hairdresser is on a break', 'To read a magazine', 'Because it is raining'], correctIndex: 0 },\n        { question: 'What can we infer about the result?', questionPt: 'O que podemos inferir sobre o resultado?', options: ['She hates it', 'She thinks it is too short', 'She is very happy with her new hair', 'She wants to change it back'], correctIndex: 2 },\n      ]",
    qA2: "What did the receptionist offer Julia?",
    repA2: "questionsA2: [\n        { question: 'What is the central focus of this narrative?', questionPt: 'Qual é o foco central desta narrativa?', options: ['The steps of a dramatic hair makeover at a high-end salon', 'How to cut your own hair', 'The recipe for herbal tea', 'A bad experience at a salon'], correctIndex: 0 },\n        { question: 'What is the best synonym for \"drastic\"?', questionPt: 'Qual é o melhor sinônimo para \"drastic\"?', options: ['Minor', 'Extreme and sudden', 'Slow and boring', 'Invisible'], correctIndex: 1 },\n        { question: 'Why did the hairdresser suggest blonde highlights?', questionPt: 'Por que a cabeleireira sugeriu mechas loiras?', options: ['Because they were cheaper', 'To brighten Julia\\'s complexion', 'Because she ran out of dark dye', 'Because Julia\\'s hair was falling out'], correctIndex: 1 },\n        { question: 'What does the word \"thrilled\" imply at the end?', questionPt: 'O que a palavra \"thrilled\" implica no final?', options: ['She was extremely excited and pleased', 'She was terrified and scared', 'She was bored', 'She was disappointed'], correctIndex: 0 },\n      ]"
  },
  // Carrental
  {
    qA1: "Where does Roberto go to rent a car?",
    repA1: "questionsA1: [\n        { question: 'What is the main event in the text?', questionPt: 'Qual é o evento principal no texto?', options: ['Roberto buying a new car', 'Roberto renting a car for a trip', 'Roberto fixing a scratch on his car', 'Roberto taking a taxi'], correctIndex: 1 },\n        { question: 'What does \"insurance\" mean in this story?', questionPt: 'O que significa \"insurance\" nesta história?', options: ['Extra money to protect him if the car gets damaged', 'Gasoline for the car', 'Food for the trip', 'A type of car'], correctIndex: 0 },\n        { question: 'Why does Roberto take photos of the car?', questionPt: 'Por que Roberto tira fotos do carro?', options: ['Because he likes photography', 'To have proof of the scratches before he drives it', 'Because it is a rule', 'To send to his friend'], correctIndex: 1 },\n        { question: 'What can we guess about Roberto\\'s trip?', questionPt: 'O que podemos adivinhar sobre a viagem de Roberto?', options: ['It is a one-day trip', 'It will last five days', 'He will walk', 'He doesn\\'t have a driver\\'s license'], correctIndex: 1 },\n      ]",
    qA2: "Why did Roberto upgrade from the economy car?",
    repA2: "questionsA2: [\n        { question: 'What is the general idea of this text?', questionPt: 'Qual é a ideia geral deste texto?', options: ['How to buy a car in the US', 'The details and options involved in renting a car in the US', 'Driving on the highway', 'How to fix scratches'], correctIndex: 1 },\n        { question: 'What does \"fuel efficiency\" mean?', questionPt: 'O que significa \"fuel efficiency\"?', options: ['A car that uses a lot of gas', 'A car that uses gas economically', 'A car that is very fast', 'A car that runs on water'], correctIndex: 1 },\n        { question: 'Why did Roberto choose to return the car with a full tank himself?', questionPt: 'Por que Roberto escolheu devolver o carro com o tanque cheio ele mesmo?', options: ['Because he loves gas stations', 'In order to save money', 'Because it was mandatory', 'Because the car was empty'], correctIndex: 1 },\n        { question: 'What is the purpose of inspecting the vehicle and noting scratches?', questionPt: 'Qual é o propósito de inspecionar o veículo e anotar arranhões?', options: ['To complain to the manager', 'To ensure he is not held responsible for pre-existing damage', 'To clean the car', 'To get a discount'], correctIndex: 1 },\n      ]"
  },
  // Supermarket
  {
    qA1: "What does Carla need to buy?",
    repA1: "questionsA1: [\n        { question: 'What is the main topic of the story?', questionPt: 'Qual é o tópico principal da história?', options: ['Carla shopping for food at the supermarket', 'Carla cooking dinner at home', 'Carla working as a cashier', 'Carla planting a garden'], correctIndex: 0 },\n        { question: 'What does \"dairy section\" mean?', questionPt: 'O que significa \"dairy section\"?', options: ['The place where they sell bread', 'The part of the store with milk and cheese', 'The checkout line', 'The parking lot'], correctIndex: 1 },\n        { question: 'Why does Carla look at her list again?', questionPt: 'Por que Carla olha para a lista novamente?', options: ['To see if she forgot anything', 'Because she likes reading', 'Because she has no money', 'Because the cashier asked for it'], correctIndex: 0 },\n        { question: 'What can we infer about Carla\\'s payment?', questionPt: 'O que podemos inferir sobre o pagamento de Carla?', options: ['She paid with a credit card', 'She gave the cashier a 50 dollar bill', 'She didn\\'t have enough money', 'She stole the food'], correctIndex: 1 },\n      ]",
    qA2: "How is meat measured in the US?",
    repA2: "questionsA2: [\n        { question: 'What is the primary message of this text?', questionPt: 'Qual é a mensagem principal deste texto?', options: ['How to cook American food', 'The overwhelming cultural differences in an American supermarket', 'How to use a self-checkout machine', 'The history of Whole Foods'], correctIndex: 1 },\n        { question: 'What does \"overwhelming\" mean in the first sentence?', questionPt: 'O que significa \"overwhelming\" na primeira frase?', options: ['Very intense and hard to process', 'Boring and simple', 'Small and quiet', 'Fast and easy'], correctIndex: 0 },\n        { question: 'Why was Carla confused by the pricing system?', questionPt: 'Por que Carla ficou confusa com o sistema de preços?', options: ['Because the prices were in euros', 'Because the sales tax was added only at the checkout', 'Because there were no price tags', 'Because everything was free'], correctIndex: 1 },\n        { question: 'What is the implication of using a loyalty card?', questionPt: 'Qual é a implicação de usar um cartão de fidelidade?', options: ['It costs extra money', 'It tracks her location', 'It provides financial discounts on purchases', 'It is required to enter the store'], correctIndex: 2 },\n      ]"
  }
];

let updatedCount = 0;

for (const rep of replacements) {
  // Replace A1
  const findA1 = new RegExp('questionsA1:\\s*\\[\\s*\\{\\s*question:\\s*[\'\"]' + escapeRegex(rep.qA1) + '.*?\\],?', 's');
  if (content.match(findA1)) {
    content = content.replace(findA1, rep.repA1 + ',');
    updatedCount++;
  } else {
    // try matching the first characters if it's truncated
    const shortQA1 = escapeRegex(rep.qA1.substring(0, 10));
    const fallbackA1 = new RegExp('questionsA1:\\s*\\[\\s*\\{\\s*question:\\s*[\'\"]' + shortQA1 + '.*?\\],?', 's');
    if (content.match(fallbackA1)) {
      content = content.replace(fallbackA1, rep.repA1 + ',');
      updatedCount++;
    } else {
      console.log("Could not find match for A1: " + rep.qA1);
    }
  }

  // Replace A2
  const findA2 = new RegExp('questionsA2:\\s*\\[\\s*\\{\\s*question:\\s*[\'\"]' + escapeRegex(rep.qA2) + '.*?\\],?', 's');
  if (content.match(findA2)) {
    content = content.replace(findA2, rep.repA2 + ',');
    updatedCount++;
  } else {
    const shortQA2 = escapeRegex(rep.qA2.substring(0, 10));
    const fallbackA2 = new RegExp('questionsA2:\\s*\\[\\s*\\{\\s*question:\\s*[\'\"]' + shortQA2 + '.*?\\],?', 's');
    if (content.match(fallbackA2)) {
      content = content.replace(fallbackA2, rep.repA2 + ',');
      updatedCount++;
    } else {
      console.log("Could not find match for A2: " + rep.qA2);
    }
  }
}

fs.writeFileSync('data/scenarios.ts', content, 'utf8');
console.log('Successfully updated ' + updatedCount + ' question blocks for the remaining scenarios.');
